Repository lafranceinsoumise/actionpopulaire.fr, pull requests merged in 2021-12, with the labels that each got.

#1399 Fix campaign person form image URL
  agir/people/person_forms/forms.py
  agir/people/views/form.py
Labels: bug-staging

#1403 Fix staging after merge conflicts
  agir/events/migrations/0015_eventsubtype_report_person_form.py
  agir/events/tests/test_actions.py
  agir/events/tests/test_api_views.py
  agir/people/migrations/0012_personform_short_description.py
Labels: bug-staging

#1392 Allow keyboard clicking of EventCard
  .hypothesis/examples/05ae5a533c0b69a4/cf1e29cc0d4fbdb4
  .hypothesis/examples/6e8be5e69c554c1f/fd09921ccc2ec1e4
  .hypothesis/examples/6f17816d3eb35872/aad70891237d7aa3
  .hypothesis/examples/8c5cf6277a8ac235/620d4155c837003a
  .hypothesis/examples/b9d64d99186294e7/85340488c27f3323
  agir/front/components/app/Link.js
  agir/front/components/genericComponents/EventCard.js
Labels: minor bug

#1406 Fix campaign person form
  .hypothesis/examples/8c5cf6277a8ac235/0214274bb5167922
  .hypothesis/examples/f39eb4bec40384d6/4c18b7563cafbb20
  agir/mailing/static/mosaico_templates/versafix-jlm2022/template.html
  agir/people/person_forms/display.py
  agir/people/tests/test_person_forms.py
Labels: bug-staging

#1409 Refactor msgs admin pages to add filters and search
  agir/msgs/admin.py
Labels: do not merge, wait next release

#1394 Update npm dependencies + browserlist DB
  package-lock.json
  package.json
Labels: javascript, dependencies

#1414 Fix object spread errors in group creation page
  agir/groups/templates/groups/create.html
Labels: minor bug

#1416 Donations : fix email 2022
  agir/donations/tasks.py
Labels: minor bug

#1415 Fix RangeError in DonateCard currency formatting `ACTIONPOPULAIRE-FRONT-1N3`
  .hypothesis/examples/05ae5a533c0b69a4/8ce97dfa7888dd90
  .hypothesis/examples/05ae5a533c0b69a4/cfa079fc25ca35cc
  .hypothesis/examples/6f17816d3eb35872/87d1a3e0d7995c67
  .hypothesis/examples/80fbecba29df1522/7a1c44e21f1adbb8
  .hypothesis/examples/f39eb4bec40384d6/8aa28d66c33a6c22
  agir/front/components/ActionToolsPage/DonateCard.js
Labels: minor bug

#1417 Fix preloaded SWR API request unhandled errors
  agir/front/components/allPages/SWRContext.js
Labels: minor bug

#1418 Fix `nouveaux_soutiens` weekly stats queryset
  .hypothesis/examples/6e8be5e69c554c1f/9fbe716a00442d13
  .hypothesis/examples/8c5cf6277a8ac235/34cd0be1286a1dc3
  agir/lib/stats.py
  agir/people/model_fields.py
Labels: minor bug

#1420 Fix `the request's session was deleted before the request completed` error
  .hypothesis/examples/b48bda71ee0ad32b/befb17f86023af47
  agir/front/components/authentication/Connexion/Logout.js
Labels: minor bug

#1419 Avoid copying to clipboard on focus in ShareLink component
  .hypothesis/examples/6e8be5e69c554c1f/9a627bacae4d5410
  .hypothesis/examples/6f17816d3eb35872/eb1cdccb9948838d
  .hypothesis/examples/8c5cf6277a8ac235/2f5f5429bf5e0879
  .hypothesis/examples/f39eb4bec40384d6/225abe7ac5bac157
  agir/front/components/genericComponents/ShareLink.js
Labels: bug

#1428 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1427 Add margin bottom to MobileActionToolsPage + fix typo in DonateCard
  agir/front/components/ActionToolsPage/DonateCard.js
  agir/front/components/ActionToolsPage/MobileActionToolsPage.js
Labels: minor bug

#1430 Fix iCalendar link on calendar page subscribe modal
  agir/events/templates/events/calendar.html
Labels: minor bug

#1434 Whitelist event fields that are editable only before the event's end
  .hypothesis/examples/05ae5a533c0b69a4/b09a1196d03c9a2b
  .hypothesis/examples/6e8be5e69c554c1f/f6d067e6da6dcad5
  agir/events/serializers.py
Labels: bug

#1426 Fix ActionButtons left and right limit gradient color (safari)
  agir/front/components/app/ActionButtons/ActionButtons.js
Labels: minor bug

#1432 Ask confirmation before sending a campaign whose subscribers have no newsletter subscription
  .hypothesis/examples/05ae5a533c0b69a4/2e92a5b646fbc2e8
  .hypothesis/examples/5b721dd590d22e25/0330c7dd51f28754
  .hypothesis/examples/5b721dd590d22e25/380a8a9d17274210
  .hypothesis/examples/80fbecba29df1522/f6fe44a5be2b58be
  .hypothesis/examples/8c5cf6277a8ac235/3f714a9a54c4b0a8
  .hypothesis/examples/b9d64d99186294e7/ea066fd8a3ee8c3d
  agir/api/settings.py
  agir/mailing/admin.py
  agir/mailing/templates/admin/send_campaign_action_confirmation.html
  agir/mailing/tests.py
Labels: performance

#1441 Use payment type configured thank you email template code
  .hypothesis/examples/6e8be5e69c554c1f/81b19ab848e771ab
  .hypothesis/examples/80fbecba29df1522/c555814713d584c4
  .hypothesis/examples/f39eb4bec40384d6/adea12544a24e22f
  .hypothesis/examples/f39eb4bec40384d6/feaf6a43638a59ef
  agir/donations/tasks.py
  agir/donations/views/donations_views.py
Labels: minor bug

#1443 fix: use fixed versions instead of `last n versions` in es2015 browserlist
  package-lock.json
  webpack.common.js
Labels: bug

#1445 Add support for Safari > 11
  webpack.common.js
Labels: bug, bug-staging

#1450 Fix contact creation page crash on country change
  agir/people/components/contacts/CreateContactPage/ContactForm.js
Labels: bug

#1446 Allow locking event edition through subtype config
  .hypothesis/examples/05ae5a533c0b69a4/132ed56c14925197
  .hypothesis/examples/6f17816d3eb35872/065e08b162d0dff8
  .hypothesis/examples/8c5cf6277a8ac235/108023e1177ff89a
  .hypothesis/examples/8c5cf6277a8ac235/52466dd72914ef61
  .hypothesis/examples/8c5cf6277a8ac235/c2d0dfed9f808c9f
  .hypothesis/examples/b48bda71ee0ad32b/5026ca90857404c1
  .hypothesis/examples/b9d64d99186294e7/e572623af849e1f6
  agir/events/components/EventSettings/EventCancelation.js
  agir/events/components/EventSettings/EventContact.js
  agir/events/components/EventSettings/EventFeedback.js
  agir/events/components/EventSettings/EventGeneral.js
  agir/events/components/EventSettings/EventLocation.js
  agir/events/components/EventSettings/EventSettings.js
  agir/events/components/EventSettings/EventVisio.js
  agir/events/components/EventSettings/routes.config.js
  agir/events/components/common/api.js
  agir/events/components/eventRequiredDocuments/EventRequiredDocuments.js
  agir/events/migrations/0016_eventsubtype_is_editable.py
  agir/events/models.py
  agir/events/rules.py
  agir/events/serializers.py
  agir/events/tests/test_rules.py
  agir/events/views/api_views.py
  agir/front/components/genericComponents/ObjectManagement/ManagementMenu.js
  agir/front/components/genericComponents/ObjectManagement/ObjectManagement.js
Labels: minor bug

#1451 Add email template and from to 2022 subscription payment type
  .hypothesis/examples/5b721dd590d22e25/d1fa5791f01a7ae7
  .hypothesis/examples/80fbecba29df1522/ecfd9a452bd2dd64
  .hypothesis/examples/8c5cf6277a8ac235/2a7146b7b566a7d4
  .hypothesis/examples/b48bda71ee0ad32b/60db077a360a242a
  .hypothesis/examples/f39eb4bec40384d6/4719baf4726afce6
  agir/donations/tasks.py
  agir/presidentielle2022/apps.py
Labels: bug

#1449 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1455 Fix ACTIONPOPULAIRE-2G - finish ongoing session requests before logging the user out
  .hypothesis/examples/8c5cf6277a8ac235/93eddfacac5d0ebd
  agir/front/components/authentication/Connexion/Logout.js
Labels: minor bug

#1456 Reduce the number of SQL requests for the admin people person list page
  agir/people/admin/panels.py
Labels: performance

#1457 Display ObjectManagement warning on small screens
  agir/front/components/genericComponents/ObjectManagement/ObjectManagement.js
Labels: bug-staging

#1460 fix: ensure payment type template and email_from are not set to None
  .hypothesis/examples/80fbecba29df1522/a53c539929704383
  .hypothesis/examples/8c5cf6277a8ac235/4753dce850b4fa61
  .hypothesis/examples/8c5cf6277a8ac235/fa836cc05939fc65
  agir/donations/tasks.py
Labels: bug, Quickfix

#1458 Add read-only `_email` field to Person model to avoid subquery personemail too often
  .hypothesis/examples/5b721dd590d22e25/19a726fab9798cf9
  .hypothesis/examples/5b721dd590d22e25/1a3acc20e1cc16d3
  .hypothesis/examples/5b721dd590d22e25/efff89c11051eefe
  .hypothesis/examples/80fbecba29df1522/6c31fa6de523fd49
  .hypothesis/examples/80fbecba29df1522/a1b572eafac76f46
  .hypothesis/examples/8c5cf6277a8ac235/9b1c83d06a5e7759
  .hypothesis/examples/8c5cf6277a8ac235/f6a98f8f9065cba8
  .hypothesis/examples/b9d64d99186294e7/2581250b4a165435
  .hypothesis/examples/b9d64d99186294e7/a5c88fabdab4014b
  .hypothesis/examples/b9d64d99186294e7/a663f3c4c6205591
  agir/elus/admin/views.py
  agir/people/actions/management.py
  agir/people/admin/panels.py
  agir/people/migrations/0013_person__email.py
  agir/people/models.py
  agir/people/tests/test_models.py
Labels: performance

#1470 Include bounced email as Person _email field value
  agir/people/migrations/0013_person__email.py
Labels: performance, bug-staging

#1471 Messages admin add filter for private types
  agir/msgs/admin.py
Labels: feature, do not merge

#1474 Fix wrong event doc reminder activity types
  agir/events/actions/notifications.py
  agir/events/management/commands/send_event_required_document_reminders.py
Labels: bug, Quickfix

#1476 Fix: send private message from joinGroup modal
  agir/groups/components/groupPage/GroupUserActions/JoinGroupDialog.js
Labels: bug-staging

#1469 Try to improve event page load speed
  agir/activity/components/common/hooks.js
  agir/authentication/views/api_views.py
  agir/front/components/ActionToolsPage/index.js
  agir/front/components/app/routes.config.js
  agir/front/components/genericComponents/BottomSheet.js
  agir/front/components/genericComponents/ShareLink.js
  agir/front/components/offline/hooks.js
  agir/front/templates/front/base_layout.html
  agir/front/templates/front/react_view.html
  agir/groups/components/groupComponents/GroupCard.js
  agir/msgs/components/common/hooks.js
  webpack.common.js
Labels: performance

#1483 Ensure _email field is set upon person creation
  .hypothesis/examples/6e8be5e69c554c1f/893d92564cdef36c
  .hypothesis/examples/8c5cf6277a8ac235/524cc8313554719b
  .hypothesis/examples/b48bda71ee0ad32b/c04bb8315aa005e9
  .hypothesis/examples/b9d64d99186294e7/1e343965d2ef6782
  .hypothesis/examples/f39eb4bec40384d6/14b837b7b9bb76c9
  .hypothesis/examples/f39eb4bec40384d6/6a1e068cc2710b67
  agir/people/models.py
  agir/people/tests/test_admin.py
  agir/people/tests/test_models.py
Labels: bug, Quickfix

#1484 Fix event creation unload handling
  agir/events/components/createEventPage/CreateEvent.js
  agir/events/components/createEventPage/EventForm/index.js
  agir/front/components/app/UnloadPrompt.js
Labels: bug-staging

#1488 Fix reate event error with form data and null organizer group
  agir/events/serializers.py
Labels: bug

#1485 Allow adding photos outside event settings only after the event
  agir/events/components/eventPage/EventPhotosCard.js
Labels: minor bug

#1481 Fix ACTIONPOPULAIRE-FRONT-1N3 Sentry issue
  agir/front/components/ActionToolsPage/DonateCard.js
Labels: minor bug

#1491 Fix message email: no membership when author not from group
  agir/groups/display.py
  agir/groups/tasks.py
Labels: bug

#1495 Fix sentry: read properties of undefined
  agir/front/components/formComponents/MessageModal/MessageStep.js
  agir/groups/components/groupPage/GroupUserActions/SecondaryActions.js
Labels: bug

#1493 Fix DonateCard currency format
  agir/front/components/ActionToolsPage/DonateCard.js
Labels: minor bug

#1497 Add preconnect link for Sentry URL to react_view template
  agir/front/templates/front/react_view.html
Labels: performance

#1496 Fix message comment emailing task recipient querysets
  agir/groups/tasks.py
Labels: minor bug

#1500 chore: update NPM dependencies
  package-lock.json
  package.json
  webpack.common.js
Labels: javascript, dependencies
