Repository lafranceinsoumise/actionpopulaire.fr, pull requests merged in 2021-06, with the labels that each got.

#698 Page `Messages` : retours
  agir/front/components/allPages/TopBar/TopBar.js
  agir/front/components/allPages/TopBar/TopBarMainLink.js
  agir/front/components/app/hooks.js
  agir/front/components/formComponents/Comment.js
  agir/front/components/genericComponents/MessageCard.js
  agir/front/components/genericComponents/grid.js
  agir/msgs/components/MessagePage/MessageThreadList.js
  agir/notifications/serializers/activity_notifications.py
Labels: feature

#705 Fix new message comment styles
  agir/front/components/formComponents/Comment.js
Labels: feature

#704 Prevent app loader from blocking the page interactions if removal fails
  agir/front/components/app/Router.js
  agir/front/templates/front/includes/loader.html
Labels: bug

#711 Post-prod message page fixes
  agir/front/components/genericComponents/Panel.js
  agir/front/views.py
  agir/msgs/components/hooks.js
  agir/msgs/rules.py
Labels: bug

#699 Fix broken unsubscribe links in email templates
  agir/lib/templates/mail_templates/EXISTING_EMAIL_SUBSCRIPTION.html
  agir/lib/templates/mail_templates/GROUP_SOMEONE_JOINED_NOTIFICATION.html
  agir/lib/templates/mail_templates/SUBSCRIPTION_CONFIRMATION_MESSAGE.html
  agir/lib/templates/mail_templates/UNEXISTING_EMAIL_LOGIN.html
Labels: bug

#702 Use image thumbnail variation as illustration in EventSerializer
  agir/events/components/eventPage/EventDescription.js
  agir/events/components/eventPage/EventDescription.stories.js
  agir/events/components/eventPage/EventPage.js
  agir/events/serializers.py
  agir/front/components/genericComponents/EventCard.js
  agir/front/components/genericComponents/EventCard.stories.js
Labels: performance

#700 Remove StaticMap marker animation
  agir/carte/components/common/Map/StaticMap.js
  agir/events/components/eventPage/EventPage.js
  agir/groups/components/groupPage/GroupBanner.js
  agir/groups/components/groupPage/GroupSuggestionCard.js
Labels: performance

#707 Fix push notification event dates' timezone
  agir/notifications/serializers/activity_notifications.py
Labels: bug

#710 Refactor useCopyToClipboard custom hook
  agir/front/components/genericComponents/tests/useCopyToClipboard.test.js
  agir/front/components/genericComponents/useCopyToClipboard.js
Labels: bug

#709 Unsubscribe view actually unsubscribes from newsletters
  agir/authentication/tests/tests.py
  agir/people/forms/subscription.py
  agir/people/templates/people/unsubscribe.html
  agir/people/views/subscription.py
Labels: bug

#701 Self-host Poppins Google font
  agir/front/components/allPages/fonts/fonts.css
  agir/front/components/allPages/fonts/poppins-300.eot
  agir/front/components/allPages/fonts/poppins-300.svg
  agir/front/components/allPages/fonts/poppins-300.ttf
  agir/front/components/allPages/fonts/poppins-300.woff
  agir/front/components/allPages/fonts/poppins-300.woff2
  agir/front/components/allPages/fonts/poppins-300italic.eot
  agir/front/components/allPages/fonts/poppins-300italic.svg
  agir/front/components/allPages/fonts/poppins-300italic.ttf
  agir/front/components/allPages/fonts/poppins-300italic.woff
  agir/front/components/allPages/fonts/poppins-300italic.woff2
  agir/front/components/allPages/fonts/poppins-500.eot
  agir/front/components/allPages/fonts/poppins-500.svg
  agir/front/components/allPages/fonts/poppins-500.ttf
  agir/front/components/allPages/fonts/poppins-500.woff
  agir/front/components/allPages/fonts/poppins-500.woff2
  agir/front/components/allPages/fonts/poppins-500italic.eot
  agir/front/components/allPages/fonts/poppins-500italic.svg
  agir/front/components/allPages/fonts/poppins-500italic.ttf
  agir/front/components/allPages/fonts/poppins-500italic.woff
  agir/front/components/allPages/fonts/poppins-500italic.woff2
  agir/front/components/allPages/fonts/poppins-600.eot
  agir/front/components/allPages/fonts/poppins-600.svg
  agir/front/components/allPages/fonts/poppins-600.ttf
  agir/front/components/allPages/fonts/poppins-600.woff
  agir/front/components/allPages/fonts/poppins-600.woff2
  agir/front/components/allPages/fonts/poppins-600italic.eot
  agir/front/components/allPages/fonts/poppins-600italic.svg
  agir/front/components/allPages/fonts/poppins-600italic.ttf
  agir/front/components/allPages/fonts/poppins-600italic.woff
  agir/front/components/allPages/fonts/poppins-600italic.woff2
  agir/front/components/allPages/fonts/poppins-700.eot
  agir/front/components/allPages/fonts/poppins-700.svg
  agir/front/components/allPages/fonts/poppins-700.ttf
  agir/front/components/allPages/fonts/poppins-700.woff
  agir/front/components/allPages/fonts/poppins-700.woff2
  agir/front/components/allPages/fonts/poppins-700italic.eot
  agir/front/components/allPages/fonts/poppins-700italic.svg
  agir/front/components/allPages/fonts/poppins-700italic.ttf
  agir/front/components/allPages/fonts/poppins-700italic.woff
  agir/front/components/allPages/fonts/poppins-700italic.woff2
  agir/front/components/allPages/fonts/poppins-italic.eot
  agir/front/components/allPages/fonts/poppins-italic.svg
  agir/front/components/allPages/fonts/poppins-italic.ttf
  agir/front/components/allPages/fonts/poppins-italic.woff
  agir/front/components/allPages/fonts/poppins-italic.woff2
  agir/front/components/allPages/fonts/poppins-regular.eot
  agir/front/components/allPages/fonts/poppins-regular.svg
  agir/front/components/allPages/fonts/poppins-regular.ttf
  agir/front/components/allPages/fonts/poppins-regular.woff
  agir/front/components/allPages/fonts/poppins-regular.woff2
  agir/front/components/app/index.js
  agir/front/components/legacyPages/index.js
  agir/front/templates/front/base_layout.html
  agir/front/templates/front/iframe_layout.html
  agir/front/templates/front/includes/gfonts.html
  agir/front/templates/front/nsp_layout.html
Labels: performance

#712 add right margin to the navbar butons on smalls desktops
  agir/front/components/allPages/TopBar/TopBar.js
Labels: javascript

#730 Update React to v17 + other minor package updates
  agir/donations/components/donationForm/AmountWidget.test.js
  agir/donations/components/donationForm/TypeWidget.test.js
  agir/front/components/genericComponents/tests/ActionCard.test.js
  agir/front/components/genericComponents/tests/Announcement.test.js
  agir/front/components/theme/_variables.scss
  agir/groups/components/groupSelector/GroupSelector.test.js
  agir/lib/components/IBANField/tests/IBAN-field.test.js
  agir/lib/components/utils/url.test.js
  package-lock.json
  package.json
Labels: dependencies, javascript

#734 Add `font-display: fallback` to font.css
  agir/front/components/allPages/fonts/fonts.css
Labels: performance

#731 Create ping API endpoint to allow caching of the session
  agir/authentication/urls.py
  agir/authentication/views/api_views.py
  agir/front/components/offline/hooks.js
  agir/front/components/serviceWorker/serviceWorker.js
Labels: bug

#738 Offline display fixes
  agir/activity/components/ActivityPage/ActivityList.js
  agir/events/components/eventPage/EventPage.js
  agir/front/components/app/ConnectivityWarning.js
  agir/front/components/notFoundPage/NotFoundPage.js
  agir/front/components/offline/hooks.js
  agir/groups/components/groupPage/GroupMessagePage/index.js
  agir/groups/components/groupPage/GroupPage/GroupPage.js
  agir/groups/components/groupPage/hooks/group.js
  agir/msgs/components/MessagePage/MessagePage.js
Labels: bug

#741 Fix top bar main link overflow
  agir/front/components/allPages/TopBar/TopBar.js
Labels: bug

#748 Fix broken storybook imports
  agir/front/components/dashboardComponents/Announcements.js
  agir/front/components/dashboardComponents/Navigation.stories.js
Labels: bug

#727 Remove event 2022/LFI distinction
  agir/carte/tests/test_views.py
  agir/carte/views.py
  agir/events/admin/panels.py
  agir/events/components/agendaPage/Agenda.js
  agir/events/components/createEventPage/EventForm/ForUsersField.js
  agir/events/components/createEventPage/EventForm/eventForm.config.js
  agir/events/components/createEventPage/EventForm/index.js
  agir/events/components/eventPage/EventHeader.js
  agir/events/components/eventPage/EventInfoCard.js
  agir/events/components/eventPage/EventPage.js
  agir/events/forms.py
  agir/events/migrations/0007_for_users_all_events.py
  agir/events/models.py
  agir/events/serializers.py
  agir/events/tests/test_api_views.py
  agir/events/tests/test_views.py
  agir/events/views/api_views.py
  agir/events/views/event_views.py
  agir/front/components/mockData/events.json
  agir/front/tests.py
  agir/notifications/management/commands/suggest_event.py
  agir/people/tests/test_views.py
  agir/people/views/dashboard.py
Labels: feature

#761 Replace NSP logo image
  agir/front/components/app/Homepage/HomeExternalLinks.js
  agir/front/components/genericComponents/logos/melenchon2022.svg
  agir/front/components/genericComponents/logos/noussommespour.svg
Labels: feature

#762 Update materiel, resources, donations links
  agir/authentication/serializers.py
  agir/groups/serializers.py
Labels: feature

#764 Replace nsp with jlm2022 links
  agir/activity/tests.py
  agir/donations/base_forms.py
  agir/elus/components/parrainages/FicheElu.js
  agir/elus/components/parrainages/Header.js
  agir/front/components/dashboardComponents/Footer.js
  agir/front/components/dashboardComponents/Footer.stories.js
  agir/front/components/globalContext/nonReactRoutes.config.js
  agir/lib/templates/mail_templates/LOGIN_SIGN_UP_MESSAGE.html
  agir/lib/templates/mail_templates/LOGIN_SIGN_UP_MESSAGE.txt
  agir/lib/templates/mail_templates/SUBSCRIPTION_CONFIRMATION_NSP_MESSAGE.html
  agir/lib/templates/mail_templates/SUBSCRIPTION_CONFIRMATION_NSP_MESSAGE.txt
  agir/people/actions/subscription.py
  agir/people/forms/profile.py
Labels: feature

#754 Refactor TellMorePage to split campaign and newsletter choices
  agir/front/components/authentication/Connexion/TellMore/ChooseCampaign.js
  agir/front/components/authentication/Connexion/TellMore/ChooseNewsletters.js
  agir/front/components/authentication/Connexion/TellMore/TellMorePage.js
Labels: feature
