Repository lafranceinsoumise/actionpopulaire.fr, pull requests merged in 2021-10, with the labels that each got.

#1119 Allow group managers to delete other manager messages
  .hypothesis/examples/11df7d079d02551f/b3e92d25ef0f6b52
  .hypothesis/examples/2499c634378930d7/a498329ed3d195ec
  .hypothesis/examples/8fff0484ee02bf26/c0abaf7b782319f2
  agir/groups/components/groupPage/hooks/messages.js
  agir/groups/rules.py
  agir/groups/tests/test_messages_api.py
Labels: minor bug

#1118 Fix .ics attachment in event related email messages
  .hypothesis/examples/11df7d079d02551f/7cd32a281501a15a
  agir/events/models.py
  agir/events/tasks.py
  agir/lib/html.py
Labels: minor bug

#1121 Create contact page more fixes
  agir/events/components/agendaPage/Agenda.js
  agir/front/components/app/routes.config.js
  agir/front/components/genericComponents/FilterTabs.js
  agir/front/components/genericComponents/Onboarding.js
  agir/people/components/contacts/CreateContactPage/ContactForm.js
  agir/people/components/contacts/CreateContactPage/HowTo.js
Labels: feature

#1122 Refactor Agenda page layout / styles
  agir/events/components/agendaPage/Agenda.js
  agir/events/components/common/UpcomingEvents/MiniEventCard.js
  agir/events/components/common/UpcomingEvents/UpcomingEvents.js
  agir/events/components/common/UpcomingEvents/UpcomingEvents.stories.js
  agir/events/components/common/UpcomingEvents/index.js
  agir/events/components/eventRequiredDocuments/MissingDocuments/MissingDocumentWarning.js
  agir/front/components/dashboardComponents/Layout/DesktopLayout.js
  agir/front/components/dashboardComponents/Layout/MobileLayout.js
  agir/front/components/genericComponents/EventCard.js
  agir/front/components/genericComponents/FilterTabs.js
  agir/front/components/genericComponents/Onboarding.js
Labels: feature

#1126 Bug when toast.tags dont exist
  agir/front/components/globalContext/Toast.js
Labels: bug-staging

#1127 Create contact page updates / fixes
  .hypothesis/examples/11df7d079d02551f/075e3f8f0e91d392
  .hypothesis/examples/11df7d079d02551f/92efbb4be721f630
  .hypothesis/examples/2499c634378930d7/1833948dec788802
  .hypothesis/examples/a0d73d1934974dad/0c0fe90dec368777
  .hypothesis/examples/a0d73d1934974dad/1c34f95097715c42
  agir/events/components/agendaPage/Agenda.js
  agir/front/components/app/ActionButtons.js
  agir/front/components/app/routes.config.js
  agir/front/urls.py
  agir/groups/migrations/0007_add_fields_to_membership.py
  agir/groups/models.py
  agir/notifications/signals.py
  agir/people/components/contacts/CreateContactPage/ConfirmContact.js
  agir/people/components/contacts/CreateContactPage/ConfirmContact.stories.js
  agir/people/components/contacts/CreateContactPage/ContactForm.js
  agir/people/components/contacts/CreateContactPage/ContactSuccess.js
  agir/people/components/contacts/CreateContactPage/ContactSuccess.stories.js
  agir/people/components/contacts/CreateContactPage/api.js
  agir/people/components/contacts/CreateContactPage/index.js
  agir/people/serializers.py
  agir/people/tests/test_api.py
  agir/people/urls.py
Labels: feature

#1129 chore: update minor NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1131 New donation page
  .hypothesis/examples/0b93d766ca628f1c/16543fb3a1833218
  .hypothesis/examples/0b93d766ca628f1c/e295563b2de409d5
  .hypothesis/examples/2499c634378930d7/c4cbc5188df064c8
  .hypothesis/examples/a0d73d1934974dad/2bdd7fd83681fbe2
  agir/activity/components/common/activity.config.js
  agir/api/settings.py
  agir/authentication/serializers.py
  agir/donations/__init__.py
  agir/donations/base_views.py
  agir/donations/components/donationPage/AmountStep.js
  agir/donations/components/donationPage/AmountStep.stories.js
  agir/donations/components/donationPage/AmountWidget.js
  agir/donations/components/donationPage/AmountWidget.stories.js
  agir/donations/components/donationPage/ByMonthWidget.js
  agir/donations/components/donationPage/DonationPage.js
  agir/donations/components/donationPage/GroupPercentageWidget.js
  agir/donations/components/donationPage/StyledComponents.js
  agir/donations/components/donationPage/api.js
  agir/donations/components/donationPage/config.js
  agir/donations/components/donationPage/images/Don_2022_BG_D.jpg
  agir/donations/components/donationPage/images/Don_2022_BG_M.jpg
  agir/donations/components/donationPage/images/Don_FI_BG_D.jpg
  agir/donations/components/donationPage/images/Don_FI_BG_M.jpg
  agir/donations/components/donationPage/images/accepted-payment-methods.svg
  agir/donations/forms.py
  agir/donations/serializers.py
  agir/donations/templates/donations/personal_information_2022.html
  agir/donations/tests/test_donations_usecases.py
  agir/donations/urls.py
  agir/donations/views/__init__.py
  agir/donations/views/api_views.py
  agir/donations/views/donations_views.py
  agir/events/components/eventPage/EventHeader.js
  agir/front/components/app/Link.js
  agir/front/components/app/routes.config.js
  agir/front/components/authentication/Connexion/Login.js
  agir/front/components/authentication/Connexion/Signup.js
  agir/front/components/formComponents/RadioField.js
  agir/front/components/genericComponents/_variables.scss
  agir/front/components/globalContext/nonReactRoutes.config.json
  agir/front/urls.py
  agir/front/views.py
  agir/groups/components/groupPage/GroupDonation.js
  agir/groups/components/groupPage/GroupPage/DesktopGroupPage.js
  agir/groups/components/groupPage/GroupPage/Routes/InfoRoute.js
  agir/groups/components/groupPage/GroupSettings/GroupFinancePage.js
  agir/groups/components/groupPage/GroupUserActions/AnonymousActions.js
  agir/groups/components/groupPage/GroupUserActions/SecondaryActions.js
  agir/groups/serializers.py
  agir/lib/components/utils/url.js
Labels: feature

#1138 Create contact page SAV
  agir/api/settings.py
  agir/front/components/app/routes.config.js
  agir/front/urls.py
  agir/lib/templates/mail_templates/NEW_CONTACT_PERSON_2022_SUBSCRIPTION.html
  agir/people/components/contacts/CreateContactPage/ContactForm.js
  agir/people/components/contacts/CreateContactPage/index.js
  agir/people/tasks.py
Labels: minor bug

#1141 Hide side column rsvped event title if empty
  agir/front/components/dashboardComponents/Layout/DesktopLayout.js
Labels: bug

#1169 Add 2022 subscription descriptions in profile page
  agir/donations/templates/donations/subscription_description.html
Labels: bug-staging

#1183 chore: update NPM dependencies (minor updates)
  package-lock.json
  package.json
Labels: javascript, dependencies

#1186 Add cache key to person image filename pattern
  agir/people/migrations/0007_add_person_image_filename_cache_key.py
  agir/people/models.py
Labels: minor bug

#1164 Refactor desktop dashboard layout to fix side column widhts
  agir/front/components/app/Footer/Footer.js
  agir/front/components/dashboardComponents/Layout/DesktopLayout.js
Labels: minor bug

#1192 Center content of modal confirmation
  agir/front/components/genericComponents/ModalConfirmation.js
Labels: webdesign

#1205 Fix 2022 subscription thank you message
  agir/donations/templates/donations/thanks.html
Labels: bug-staging

#1203 Add white background to Avatars component images
  agir/front/components/genericComponents/Avatars.js
Labels: minor bug

#1208 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1196 Refactor dashboard layout and nav
  agir/activity/components/ActivityPage/ActivityList.js
  agir/events/components/agendaPage/Agenda.js
  agir/events/components/agendaPage/AgendaPage.js
  agir/events/components/eventPage/EventPage.stories.js
  agir/events/components/eventRequiredDocuments/MissingDocuments/MissingDocumentWarning.js
  agir/front/components/allPages/TopBar.js
  agir/front/components/app/ActionButtons.js
  agir/front/components/app/Announcements.js
  agir/front/components/app/FacebookLoginAd.js
  agir/front/components/app/Layout/CenteredLayout.js
  agir/front/components/app/Layout/DesktopLayout.js
  agir/front/components/app/Layout/Layout.js
  agir/front/components/app/Layout/MobileLayout.js
  agir/front/components/app/Layout/StyledComponents.js
  agir/front/components/app/Layout/index.js
  agir/front/components/app/Navigation/BottomBar/BottomBar.js
  agir/front/components/app/Navigation/BottomBar/BottomBar.stories.js
  agir/front/components/app/Navigation/BottomBar/index.js
  agir/front/components/app/Navigation/CounterBadge.js
  agir/front/components/app/Navigation/CounterBadge.stories.js
  agir/front/components/app/Navigation/SideBar/SecondaryMenu.js
  agir/front/components/app/Navigation/SideBar/SideBar.js
  agir/front/components/app/Navigation/SideBar/SideBar.stories.js
  agir/front/components/app/Navigation/SideBar/index.js
  agir/front/components/app/Navigation/TopBar/DesktopNavBar/AdminLink.js
  agir/front/components/app/Navigation/TopBar/DesktopNavBar/DesktopNavBar.js
  agir/front/components/app/Navigation/TopBar/DesktopNavBar/DesktopNavBar.stories.js
  agir/front/components/app/Navigation/TopBar/DesktopNavBar/RightLinks.js
  agir/front/components/app/Navigation/TopBar/DesktopNavBar/SearchBar.js
  agir/front/components/app/Navigation/TopBar/MobileNavBar/DashboardPageBar.js
  agir/front/components/app/Navigation/TopBar/MobileNavBar/DashboardPageBar.stories.js
  agir/front/components/app/Navigation/TopBar/MobileNavBar/MobileNavBar.js
  agir/front/components/app/Navigation/TopBar/MobileNavBar/RightLink.js
  agir/front/components/app/Navigation/TopBar/MobileNavBar/SecondaryPageBar.js
  agir/front/components/app/Navigation/TopBar/MobileNavBar/SecondaryPageBar.stories.js
  agir/front/components/app/Navigation/TopBar/MobileNavBar/StyledBar.js
  agir/front/components/app/Navigation/TopBar/NavBar.js
  agir/front/components/app/Navigation/TopBar/TopBar.js
  agir/front/components/app/Navigation/TopBar/UserMenu.js
  agir/front/components/app/Navigation/TopBar/index.js
  agir/front/components/app/Navigation/index.js
  agir/front/components/app/Navigation/navigation.config.json
  agir/front/components/app/Page.js
  agir/front/components/app/Router.js
  agir/front/components/app/routes.config.js
  agir/front/components/authentication/Connexion/AuthenticatedLogin.js
  agir/front/components/dashboardComponents/Navigation.js
  agir/front/components/dashboardComponents/Navigation.stories.js
  agir/front/components/genericComponents/EventCard.js
  agir/front/components/genericComponents/RenderIfVisible.js
  agir/front/components/genericComponents/_variables.scss
  agir/front/components/legacyPages/renderLegacyPageComponents.js
  agir/front/components/mockData/routes.json
  agir/front/components/navigationPage/NavigationPage.js
  agir/front/components/notFoundPage/NotFoundPage.js
  agir/front/components/toolsPage/ToolsPage.js
  agir/groups/components/fullGroupPage/FullGroupPage.js
  agir/groups/components/groupPage/GroupMessagePage/index.js
  agir/groups/components/groupsPage/GroupsPageHeader.js
  agir/msgs/components/MessagePage/MessagePage.js
Labels: webdesign, performance

#1212 Layout and Navigation refactor fixes
  agir/events/components/agendaPage/EventSuggestions.js
  agir/front/components/app/Layout/Layout.js
  agir/front/components/app/Page.js
  agir/front/components/app/Router.js
  agir/front/components/app/routes.config.js
  agir/front/components/genericComponents/EventCard.js
Labels: bug-staging
