Repository lafranceinsoumise/actionpopulaire.fr, pull requests merged in 2021-09, with the labels that each got.

#934 fix(deps): bump workbox-* dependencies to 6.2.4
  package-lock.json
  package.json
Labels: javascript, dependencies, bug-staging

#936 chore(deps): bump up minor npm dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#939 fix CodeLogin form children alignment
  agir/front/components/authentication/Connexion/Code/CodeLogin.js
Labels: bug

#938 Fix event og-image (ACTIONPOPULAIRE-7Y)
  agir/events/views/event_views.py
  agir/front/static/front/og-image/map-marker.png
  agir/front/views.py
Labels: bug

#935 Fix webpack build - exit with code 1 if compilation has errors
  webpack.production.js
Labels: bug

#928 Add logs for 404
  agir/front/components/notFoundPage/NotFoundPage.js
Labels: wait next release

#953 fix: add ignored Outlook-related error message to Sentry config (ACTIONPOPULAIRE-FRONT-10Y)
  agir/front/components/allPages/sentry.js
Labels: bug

#960 Update npm dependencies
  agir/activity/components/common/hooks.js
  agir/groups/components/groupPage/GroupSuggestions.js
  agir/groups/components/groupPage/hooks/events.js
  agir/groups/components/groupPage/hooks/messages.js
  package-lock.json
  package.json
Labels: javascript, dependencies

#969 Fix broken dashboard_search url config
  agir/people/urls.py
Labels: bug

#968 Factorize SWRConfig and add it to legacy pages
  agir/front/components/allPages/SWRContext.js
  agir/front/components/app/App.js
  agir/front/components/legacyPages/renderLegacyPageComponents.js
Labels: bug-staging

#976 Dynamic event og image crash - ACTIONPOPULAIRE-8B
  .hypothesis/examples/a0d73d1934974dad/96f9b0496e0027cc
  agir/events/views/event_views.py
Labels: bug

#957 Fix: show keyboard tor responding to messages on iOS
  agir/front/components/formComponents/CommentField.js
Labels: wait next release

#954 Try to speed up event suggestions API response
  agir/events/serializers.py
  agir/events/views/api_views.py
Labels: performance

#979 chore: Update webpack-dev-server to v4 + js-cookie to v3 + minor updates
  .hypothesis/examples/2499c634378930d7/cebcca6d86f7ee4f
  agir/activity/components/ActivityPage/ActivityList.js
  agir/activity/components/ActivityPage/ActivityPage.js
  agir/front/components/allPages/TopBar/DesktopNavBar/SearchBar.js
  agir/front/components/authentication/common.js
  agir/msgs/components/MessagePage/MessagePage.js
  agir/msgs/components/MessagePage/MessageThreadMenu.js
  agir/notifications/components/NotificationSettings/NotificationSettingItem.js
  agir/notifications/components/NotificationSettings/NotificationSettingItem.stories.js
  agir/notifications/components/NotificationSettings/NotificationSettingLink.js
  agir/notifications/components/NotificationSettings/NotificationSettingPanel.js
  agir/notifications/components/NotificationSettings/NotificationSettingPanel.stories.js
  agir/notifications/components/NotificationSettings/NotificationSettings.js
  package-lock.json
  package.json
  webpack.common.js
  webpack.dev.js
Labels: javascript, dependencies

#990 Upgrade react-toastify to v8
  package-lock.json
  package.json
Labels: dependencies, ready

#987 Use captureMessage to log notFoundPage into sentry
  agir/front/components/notFoundPage/NotFoundPage.js
Labels: bug-staging

#992 Fix `/api/session/` preloading (attempt no2)
  agir/front/components/allPages/SWRContext.js
  agir/front/templates/front/react_view.html
Labels: performance, minor bug

#988 Missing event suggestion distances
  .hypothesis/examples/11df7d079d02551f/7ac6f7bcdfd1aa42
  .hypothesis/examples/11df7d079d02551f/8f2ac79b28ff9b60
  agir/events/views/api_views.py
Labels: bug-staging

#991 Fix overseas phonenumber validation
  .hypothesis/examples/0b93d766ca628f1c/1a2e3bbdbab6aff6
  agir/people/model_fields.py
  poetry.lock
  pyproject.toml
Labels: python, dependencies, minor bug

#971 Various group follower membership type style/wording fixes
  agir/front/components/formComponents/MessageModal/EventStep.js
  agir/front/components/formComponents/MessageModal/GroupStep.js
  agir/front/components/mockData/group.json
  agir/groups/components/groupPage/GroupFacts.js
  agir/groups/components/groupPage/GroupFacts.stories.js
  agir/groups/components/groupPage/GroupSettings/GroupMemberPage/ConfirmPanel.js
  agir/groups/components/groupPage/GroupSettings/GroupMemberPage/MainPanel.js
  agir/groups/components/groupPage/GroupUserActions/AnonymousActions.js
  agir/groups/components/groupPage/GroupUserActions/FollowerActions.js
  agir/groups/components/groupPage/GroupUserActions/NonMemberActions.js
  agir/groups/components/groupPage/GroupUserActions/QuitGroupDialog.js
  agir/groups/models.py
  agir/groups/serializers.py
Labels: bug-staging

#993 Attempt to smooth out the app first page load
  agir/events/components/agendaPage/AgendaPage.js
  agir/front/components/allPages/TopBar/DesktopNavBar/DesktopNavBar.js
  agir/front/components/allPages/TopBar/DesktopNavBar/DesktopNavBar.stories.js
  agir/front/components/allPages/TopBar/DesktopNavBar/RightLinks.js
  agir/front/components/allPages/TopBar/MobileNavBar/DashboardPageBar.js
  agir/front/components/allPages/TopBar/MobileNavBar/DashboardPageBar.stories.js
  agir/front/components/allPages/TopBar/MobileNavBar/MobileNavBar.js
  agir/front/components/allPages/TopBar/MobileNavBar/RightLink.js
  agir/front/components/allPages/TopBar/MobileNavBar/SecondaryPageBar.js
  agir/front/components/allPages/TopBar/MobileNavBar/SecondaryPageBar.stories.js
  agir/front/components/allPages/TopBar/MobileNavBar/StyledBar.js
  agir/front/components/allPages/TopBar/TopBar.js
  agir/front/components/app/Page.js
  agir/front/components/app/Router.js
  agir/front/components/genericComponents/LogoAP.js
  agir/front/components/legacyPages/renderLegacyPageComponents.js
Labels: performance

#995 chore: NPM modules minor updates
  package-lock.json
  package.json
Labels: javascript, dependencies

#1000 Create custom phone number field to support overseas numbers
  agir/events/serializers.py
  agir/lib/serializers.py
  agir/people/serializers.py
Labels: minor bug

#1001 Broken login page on missing bookmarked emails cookie
  agir/front/components/authentication/common.js
Labels: bug-staging

#994 Display 0 distance events in the 'near' section
  agir/events/components/agendaPage/Agenda.js
Labels: minor bug

#1006 Avoid page crash on missing ResizeObserver
  agir/lib/components/utils/hooks.js
Labels: minor bug

#1005 Fix Cleave paste crashing issue (ACTIONPOPULAIRE-FRONT-12H)
  agir/front/components/formComponents/PhoneField.js
  agir/lib/components/creationForms/steps/ContactStep.js
Labels: minor bug

#1004 Remove webpack dev optimization that breaks legacy project pages
  webpack.dev.js
Labels: bug-staging

#1009 Update event subtype API call on required docs page
  agir/events/components/eventRequiredDocuments/EventRequiredDocumentsPage.js
  agir/events/components/eventRequiredDocuments/EventSubtypePicker.js
Labels: bug-staging

#1003 Centralize local storage usage to custom useLocalStorage hook
  agir/front/components/allPages/FeedbackButton.js
  agir/front/components/app/hooks.js
  agir/front/components/dashboardComponents/Navigation.js
  agir/notifications/components/push/subscriptions.js
Labels: minor bug

#1002 Update retriable_task to retry on all request timeout exceptions
  agir/lib/celery.py
Labels: minor bug

#1007 Fix ShareLink and GroupCard click event (ACTIONPOPULAIRE-FRONT-12E)
  agir/groups/components/groupComponents/GroupCard.js
Labels: minor bug

#1013 Add organizer group field to event settings
  .hypothesis/examples/11df7d079d02551f/cc96209cc63714a1
  .hypothesis/examples/a0d73d1934974dad/bc0fb73e4fc66d98
  .hypothesis/examples/a0d73d1934974dad/ee295d9267fc9538
  agir/events/components/EventSettings/EventGeneral.js
  agir/events/components/common/OrganizerGroupField.js
  agir/events/components/createEventPage/EventForm/index.js
  agir/events/serializers.py
Labels: bug-staging

#1017 chore: update npm dependencies (minor updates)
  package-lock.json
  package.json
Labels: javascript, dependencies

#1015 Update quit group dialog wording
  agir/groups/components/groupPage/GroupUserActions/QuitGroupDialog.js
Labels: bug-staging

#977 Group page updates : buttons & modal
  agir/front/components/formComponents/MessageActionModal.js
  agir/front/components/genericComponents/Button/Button.js
  agir/front/components/genericComponents/ModalConfirmation.js
  agir/front/components/genericComponents/ModalConfirmation.stories.js
  agir/front/components/genericComponents/ModalShare.js
  agir/front/components/genericComponents/ModalShare.stories.js
  agir/front/components/genericComponents/_variables.scss
  agir/groups/components/groupPage/GroupUserActions/AnonymousActions.js
  agir/groups/components/groupPage/GroupUserActions/GroupUserActions.js
  agir/groups/components/groupPage/GroupUserActions/NonMemberActions.js
  agir/groups/components/groupPage/GroupUserActions/SecondaryActions.js
  agir/groups/components/groupPage/GroupUserActions/index.js
Labels: feature

#989 Panel event: feedbacks
  .hypothesis/examples/11df7d079d02551f/cc96209cc63714a1
  .hypothesis/examples/a0d73d1934974dad/bc0fb73e4fc66d98
  .hypothesis/examples/a0d73d1934974dad/ee295d9267fc9538
  agir/events/components/EventSettings/EventContact.js
  agir/events/components/EventSettings/EventFeedback.js
  agir/events/components/EventSettings/EventGeneral.js
  agir/events/components/EventSettings/EventMember.js
  agir/events/components/EventSettings/EventOrganization.js
  agir/events/components/EventSettings/EventParticipants.js
  agir/events/components/EventSettings/EventSettings.js
  agir/events/components/EventSettings/EventSubtypeField.js
  agir/events/components/common/OrganizerGroupField.js
  agir/events/components/common/api.js
  agir/events/components/createEventPage/EventForm/index.js
  agir/events/components/eventPage/EventDescriptionCard.js
  agir/events/components/eventPage/EventHeader.js
  agir/events/components/eventPage/EventPhotosCard.js
  agir/events/components/eventPage/EventReportCard.js
  agir/events/models.py
  agir/events/serializers.py
  agir/events/urls.py
  agir/events/views/api_views.py
  agir/front/components/genericComponents/ObjectManagement/ObjectManagement.js
  agir/groups/components/groupPage/GroupSettings/GroupMember.js
  agir/lib/model_fields.py
  agir/lib/serializers.py
  agir/lib/utils.py
  package-lock.json
Labels: bug-staging

#1021 Fix rich text editor field broken HTML tags (h1, u, s)
  agir/api/settings.py
  agir/front/components/formComponents/RichText/Editor.js
Labels: minor bug

#1019 Profil image : fix image rotation
  agir/people/models.py
Labels: minor bug

#1022 Restrict event management to organizing group referents
  .hypothesis/examples/0b93d766ca628f1c/1d1071eb733c1854
  agir/events/forms.py
  agir/events/rules.py
  agir/events/serializers.py
  agir/events/tests/test_rules.py
Labels: bug-staging

#1031 Event management feedbacks : photos and wording fixes
  agir/activity/components/ActivityPage/ActivityCard/GenericCard.js
  agir/events/components/EventSettings/EventFeedback.js
  agir/events/components/EventSettings/routes.config.js
  agir/events/components/eventPage/EventPhotosCard.js
  agir/events/components/eventPage/EventReportCard.js
  agir/front/components/genericComponents/EventCard.js
  agir/groups/components/groupPage/EmptyContent.js
  agir/notifications/components/common/notifications.config.js
Labels: bug-staging

#1033 Fix route dashboard
  agir/front/components/authentication/Connexion/AuthenticatedLogin.js
Labels: bug, do not merge, wait next release

#1034 Fix event settings
  .hypothesis/examples/8fff0484ee02bf26/5722d97409b659fc
  .hypothesis/examples/a0d73d1934974dad/bada50601cae495c
  .hypothesis/examples/a0d73d1934974dad/dc7e6a26c0d0816b
  agir/events/components/EventSettings/EventContact.js
  agir/events/components/EventSettings/EventLocation.js
  agir/events/components/EventSettings/EventOrganization.js
  agir/events/components/common/api.js
  agir/events/components/createEventPage/EventForm/DateField.js
  agir/events/components/eventPage/EventPage.js
  agir/events/serializers.py
Labels: bug-staging

#1030 Page groupe : retours
  agir/front/components/genericComponents/ModalConfirmation.js
  agir/front/components/genericComponents/ModalShare.js
  agir/groups/components/groupPage/GroupUserActions/SecondaryActions.js
  agir/groups/components/groupPage/GroupUserActions/index.js
Labels: bug-staging

#1043 Fix missing contact group page crash
  agir/groups/components/groupPage/GroupUserActions/SecondaryActions.js
Labels: bug

#1044 Post-prod event settings fixes
  .hypothesis/examples/0b93d766ca628f1c/6027cf944d10c10f
  .hypothesis/examples/2499c634378930d7/570d138ec74d4fd3
  agir/events/components/EventSettings/EventContact.js
  agir/events/components/EventSettings/EventFeedback.js
  agir/events/components/EventSettings/EventGeneral.js
  agir/events/components/EventSettings/EventLocation.js
  agir/events/components/EventSettings/EventOrganization.js
  agir/events/components/EventSettings/EventParticipants.js
  agir/events/components/EventSettings/EventSettings.js
  agir/events/components/EventSettings/EventVisio.js
  agir/events/serializers.py
  agir/events/tests/test_api_views.py
  agir/front/components/formComponents/ImageField.js
  agir/front/components/formComponents/RichText/Editor.js
  agir/front/components/formComponents/SelectField.js
Labels: minor bug

#1049 Miniatures RS : fix event location and long title display
  agir/events/views/event_views.py
Labels: bug

#1051 Set overflow-y to auto for PanelWrapper component
  agir/front/components/genericComponents/ObjectManagement/PanelWrapper.js
Labels: minor bug

#1035 Allow recentering of openlayer map after center prop update
  agir/carte/components/common/Map/OpenLayersMap.js
  agir/carte/components/map/common.js
Labels: minor bug

#1053 Split and lazy load mobile/desktop dashboard layout and footer
  agir/activity/components/ActivityPage/ActivityList.js
  agir/events/components/agendaPage/Agenda.js
  agir/events/components/agendaPage/AgendaPage.js
  agir/events/components/eventPage/EventPage.js
  agir/events/components/eventRequiredDocuments/EventRequiredDocumentsPage.js
  agir/events/components/eventRequiredDocuments/MissingDocuments/MissingDocumentsPage.js
  agir/front/components/app/Footer/Footer.js
  agir/front/components/app/Footer/Footer.stories.js
  agir/front/components/app/Footer/FooterBanner.js
  agir/front/components/app/Footer/images/app-store-badge.svg
  agir/front/components/app/Footer/images/footer-banner.jpg
  agir/front/components/app/Footer/images/google-play-badge.png
  agir/front/components/app/Footer/index.js
  agir/front/components/app/Homepage/Home.js
  agir/front/components/app/IntroApp.js
  agir/front/components/app/Page.js
  agir/front/components/app/Router.js
  agir/front/components/app/routes.config.js
  agir/front/components/dashboardComponents/CenteredLayout.js
  agir/front/components/dashboardComponents/FacebookLoginAd.js
  agir/front/components/dashboardComponents/Footer.js
  agir/front/components/dashboardComponents/Layout.js
  agir/front/components/dashboardComponents/Layout.stories.js
  agir/front/components/dashboardComponents/Layout/DesktopLayout.js
  agir/front/components/dashboardComponents/Layout/Layout.js
  agir/front/components/dashboardComponents/Layout/MobileLayout.js
  agir/front/components/dashboardComponents/Layout/StyledComponents.js
  agir/front/components/dashboardComponents/Layout/index.js
  agir/front/components/globalContext/nonReactRoutes.config.json
  agir/front/components/toolsPage/ToolsPage.js
  agir/groups/components/groupPage/GroupPage/GroupPage.js
  agir/groups/components/groupsPage/GroupsPageHeader.js
Labels: javascript, performance

#1059 Fix email wording template jlm
  agir/mailing/static/mosaico_templates/versafix-jlm2022/template.html
  agir/mailing/static/mosaico_templates/versafix-nsp/template.html
Labels: minor bug

#1060 Fix: ACTIONPOPULAIRE-90
  .hypothesis/examples/2499c634378930d7/7cf3490a670e7c81
  agir/people/admin/panels.py
Labels: minor bug

#1061 Restore MessageCard text line breaks
  agir/front/components/genericComponents/MessageCard.js
  agir/front/components/genericComponents/MessageCard.stories.js
Labels: minor bug

#1058 chore: Update npm dependencies (minor updates)
  package-lock.json
  package.json
Labels: javascript, dependencies

#1064 Remove unused code
  .hypothesis/examples/8fff0484ee02bf26/1beda3f53a75ab0b
  .hypothesis/examples/a0d73d1934974dad/6e8c32c1805e776f
  agir/authentication/tests/tests.py
  agir/events/components/EventSettings/EventGeneral.js
  agir/events/components/EventSettings/EventLocation.js
  agir/events/components/EventSettings/EventOrganization.js
  agir/events/components/EventSettings/EventSettings.js
  agir/events/components/EventSettings/EventSubtypeField.js
  agir/events/components/EventSettings/routes.config.js
  agir/events/components/common/eventForm.config.js
  agir/events/components/createEventPage/EventForm/index.js
  agir/events/components/eventPage/EventReportCard.js
  agir/events/forms.py
  agir/events/templates/events/edit_event_report.html
  agir/events/templates/events/manage.html
  agir/events/templates/events/modify.html
  agir/events/tests/test_views.py
  agir/events/views/event_views.py
  agir/front/components/formComponents/ImageField.js
  agir/front/components/formComponents/RichText/Editor.js
  agir/front/components/genericComponents/ObjectManagement/ManagementMenu.js
  agir/front/components/genericComponents/ObjectManagement/ObjectManagement.js
  agir/front/tests.py
  agir/groups/components/groupPage/Announcements/DiscussionAnnouncement.js
  agir/groups/components/groupPage/Announcements/DisplayNameAnnouncement.js
  agir/groups/components/groupPage/GroupMessage.js
  agir/groups/components/groupPage/GroupMessages.js
  agir/groups/components/groupPage/GroupPage/Routes/RoutePreviews.js
  agir/groups/components/groupPage/GroupPage/index.js
  agir/groups/components/groupPage/NewGroupPageModal.js
  agir/groups/components/groupPage/NewGroupPageModal.stories.js
  agir/lib/tests/test_views.py
Labels: performance

#1065 Fix : remove space on some headers
  agir/events/components/agendaPage/AgendaPage.js
  agir/front/components/app/Homepage/Home.js
Labels: bug-staging

#1052 Replace mailto by confirmModal and email in shareLink
  agir/groups/components/groupPage/GroupUserActions/SecondaryActions.js
  agir/groups/components/groupPage/GroupUserActions/index.js
Labels: bug

#1067 Fix initial organizer group crash on event settings panel
  agir/events/components/EventSettings/EventGeneral.js
Labels: bug

#1068 Remove footer from message page
  agir/front/components/app/routes.config.js
Labels: bug-staging

#1071 Fix margin due to large button on small mobile
  agir/events/components/agendaPage/Agenda.js
Labels: webdesign

#1066 Add z-index on bottomBar
  agir/front/components/app/Page.js
  agir/front/components/dashboardComponents/Navigation.js
  agir/front/components/genericComponents/EventCard.js
  agir/front/components/genericComponents/_variables.scss
Labels: bug-staging

#1070 Fix messages refresh after message deletion
  agir/msgs/components/MessagePage/MessagePage.js
  agir/msgs/components/common/hooks.js
Labels: minor bug

#1072 Add allow_blank to unrequired SubscriptionRequestSerializer fields
  agir/groups/components/groupPage/GroupUserActions/index.js
  agir/people/serializers.py
Labels: bug

#1075 Fix ScrollMemory state
  agir/front/components/app/Router.js
Labels: minor bug

#1084 chore: update NPM dependencies (minor updates)
  package-lock.json
  package.json
Labels: javascript, dependencies

#1087 Update SUBSCRIPTION_CONFIRMATION_NSP_MESSAGE with jlm2022 logo and colors
  agir/lib/templates/mail_templates/SUBSCRIPTION_CONFIRMATION_NSP_MESSAGE.html
Labels: minor bug

#1083 Fix event Facebook short URL validation
  .hypothesis/examples/8fff0484ee02bf26/29b4b5e65a20ce01
  .hypothesis/examples/8fff0484ee02bf26/bc4ca602eff39ad8
  agir/lib/utils.py
Labels: minor bug

#1095 Revert "Merge pull request #1085 from lafranceinsoumise/gdp/add-campaign-funding-faq-links"
  agir/events/components/createEventPage/EventForm/CampaignFundingField.js
  agir/events/components/eventRequiredDocuments/MissingDocuments/MissingDocuments.js
  agir/front/components/globalContext/nonReactRoutes.config.json
Labels: bug-staging

#1096 Update SUBSCRIPTION_CONFIRMATION_NSP_MESSAGE email template
  agir/lib/templates/mail_templates/SUBSCRIPTION_CONFIRMATION_NSP_MESSAGE.html
Labels: bug-staging

#1097 Update Attestation_concours_en_nature file
  agir/front/static/front/modeles/Attestation_concours_en_nature.pdf
Labels: bug-staging

#1098 Update SUBSCRIPTION_CONFIRMATION_NSP_MESSAGE email template
  agir/api/settings.py
  agir/lib/templates/mail_templates/SUBSCRIPTION_CONFIRMATION_NSP_MESSAGE.html
Labels: bug-staging

#1094 New donation page (step 1)
  agir/activity/components/common/activity.config.js
  agir/authentication/serializers.py
  agir/donations/components/donationPage/AmountStep.js
  agir/donations/components/donationPage/AmountStep.stories.js
  agir/donations/components/donationPage/AmountWidget.js
  agir/donations/components/donationPage/AmountWidget.stories.js
  agir/donations/components/donationPage/ByMonthWidget.js
  agir/donations/components/donationPage/DonationPage.js
  agir/donations/components/donationPage/GroupPercentageWidget.js
  agir/donations/components/donationPage/StyledComponents.js
  agir/donations/components/donationPage/api.js
  agir/donations/components/donationPage/config.js
  agir/donations/components/donationPage/images/Don_2022_BG_D.jpg
  agir/donations/components/donationPage/images/Don_2022_BG_M.jpg
  agir/donations/components/donationPage/images/Don_FI_BG_D.jpg
  agir/donations/components/donationPage/images/Don_FI_BG_M.jpg
  agir/donations/components/donationPage/images/accepted-payment-methods.svg
  agir/donations/serializers.py
  agir/donations/urls.py
  agir/donations/views/__init__.py
  agir/donations/views/api_views.py
  agir/events/components/eventPage/EventHeader.js
  agir/events/components/eventRequiredDocuments/MissingDocuments/MissingDocuments.js
  agir/front/components/app/Link.js
  agir/front/components/app/routes.config.js
  agir/front/components/authentication/Connexion/Login.js
  agir/front/components/authentication/Connexion/Signup.js
  agir/front/components/formComponents/RadioField.js
  agir/front/components/genericComponents/_variables.scss
  agir/front/components/globalContext/nonReactRoutes.config.json
  agir/front/urls.py
  agir/front/views.py
  agir/groups/components/groupPage/GroupDonation.js
  agir/groups/components/groupPage/GroupPage/DesktopGroupPage.js
  agir/groups/components/groupPage/GroupPage/Routes/InfoRoute.js
  agir/groups/components/groupPage/GroupSettings/GroupFinancePage.js
  agir/groups/components/groupPage/GroupUserActions/AnonymousActions.js
  agir/groups/components/groupPage/GroupUserActions/SecondaryActions.js
  agir/groups/serializers.py
  agir/lib/components/utils/url.js
Labels: feature

#1099 Fix membership type update permissions for managers
  .hypothesis/examples/a0d73d1934974dad/ca20d43c01d146ec
  agir/groups/rules.py
  agir/groups/tests/test_api_views.py
  agir/groups/views/api_views.py
  agir/lib/tests/mixins.py
Labels: minor bug

#1100 Add uuid to ImageMixin filename pattern to force cache refresh after change
  .hypothesis/examples/11df7d079d02551f/534301703b474df5
  agir/events/migrations/0010_uuid_in_image_filename.py
  agir/groups/migrations/0006_uuid_in_image_filename.py
  agir/lib/models.py
Labels: minor bug

#1104 Fix event creation form default datetime format
  agir/events/components/common/eventForm.config.js
Labels: bug

#1105 Hide FeedbackButton on legacy custom form pages
  .hypothesis/examples/0b93d766ca628f1c/dd2b1d904a2fe949
  .hypothesis/examples/a0d73d1934974dad/347855941601853e
  agir/events/views/rsvp_views.py
  agir/front/components/legacyPages/renderLegacyPageComponents.js
  agir/front/templates/front/base_layout.html
  agir/people/views/form.py
Labels: minor bug

#1109 chore: update NPM dependecies
  package-lock.json
  package.json
  webpack.common.js
Labels: javascript, dependencies, performance

#1107 Add homepage action buttons
  agir/events/components/agendaPage/Agenda.js
  agir/front/components/allPages/TopBar/DesktopNavBar/DesktopNavBar.js
  agir/front/components/app/ActionButtons.js
  agir/front/components/app/ActionButtons.stories.js
  agir/front/components/dashboardComponents/Layout/DesktopLayout.js
Labels: feature

#1103 Create contact page
  .hypothesis/examples/11df7d079d02551f/f74bcbd5e47a1c72
  .hypothesis/examples/8fff0484ee02bf26/9f880b10bbdddd56
  agir/api/settings.py
  agir/front/components/app/routes.config.js
  agir/front/components/formComponents/PhoneField.js
  agir/front/components/formComponents/TextField.js
  agir/front/urls.py
  agir/lib/components/utils/hooks.js
  agir/lib/templates/mail_templates/NEW_CONTACT_PERSON_SUBSCRIPTION.html
  agir/lib/templates/mail_templates/NEW_CONTACT_PERSON_SUBSCRIPTION.txt
  agir/lib/templates/mail_templates/NEW_CONTACT_PERSON_UPDATE.html
  agir/lib/templates/mail_templates/NEW_CONTACT_PERSON_UPDATE.txt
  agir/people/components/contacts/CreateContactPage/ConfirmContact.js
  agir/people/components/contacts/CreateContactPage/ConfirmContact.stories.js
  agir/people/components/contacts/CreateContactPage/ContactForm.js
  agir/people/components/contacts/CreateContactPage/ContactForm.stories.js
  agir/people/components/contacts/CreateContactPage/ContactSuccess.js
  agir/people/components/contacts/CreateContactPage/ContactSuccess.stories.js
  agir/people/components/contacts/CreateContactPage/HowTo.js
  agir/people/components/contacts/CreateContactPage/HowTo.stories.js
  agir/people/components/contacts/CreateContactPage/NoGroupCard.js
  agir/people/components/contacts/CreateContactPage/NoGroupCard.stories.js
  agir/people/components/contacts/CreateContactPage/StyledComponents.js
  agir/people/components/contacts/CreateContactPage/StyledComponents.stories.js
  agir/people/components/contacts/CreateContactPage/api.js
  agir/people/components/contacts/CreateContactPage/images/bg-large.svg
  agir/people/components/contacts/CreateContactPage/images/bg-sea-large.jpg
  agir/people/components/contacts/CreateContactPage/images/bg-sea-small.jpg
  agir/people/components/contacts/CreateContactPage/images/bg-small.png
  agir/people/components/contacts/CreateContactPage/index.js
  agir/people/migrations/0006_add_newsletter_liaison_type.py
  agir/people/models.py
  agir/people/rules.py
  agir/people/serializers.py
  agir/people/tasks.py
  agir/people/tests/test_api.py
  agir/people/urls.py
  agir/people/views/api.py
Labels: feature

#1112 Replace 404 error Sentry message capturing with breadcrumbs
  agir/front/components/notFoundPage/NotFoundPage.js
Labels: bug

#1111 Update react select
  agir/groups/components/groupSelector/GroupSelector.test.js
  package-lock.json
  package.json
Labels: javascript, dependencies

#1116 Create contact page fixes
  agir/events/components/EventSettings/EventContact.js
  agir/events/components/agendaPage/Agenda.js
  agir/events/components/eventRequiredDocuments/MissingDocuments/MissingDocumentWarning.js
  agir/front/components/app/ActionButtons.js
  agir/front/components/dashboardComponents/Navigation.js
  agir/front/components/formComponents/PhoneField.js
  agir/front/components/genericComponents/FilterTabs.js
  agir/groups/components/groupPage/GroupSettings/GroupContactPage.js
  agir/people/components/contacts/CreateContactPage/ConfirmContact.js
  agir/people/components/contacts/CreateContactPage/ConfirmContact.stories.js
  agir/people/components/contacts/CreateContactPage/ContactForm.js
  agir/people/components/contacts/CreateContactPage/HowTo.js
  agir/people/components/contacts/CreateContactPage/index.js
Labels: feature, bug-staging
