Repository lafranceinsoumise/actionpopulaire.fr, pull requests merged in 2021-11, with the labels that each got.

#1271 Fix map pages broken
  agir/carte/components/common/MapPage.js
Labels: ready, minor bug

#1273 Filter event visibility admin for required_documents
  agir/events/actions/required_documents.py
  agir/events/rules.py
Labels: minor bug

#1272 Condition scroll from parent management on mobile
  agir/front/components/genericComponents/ObjectManagement/ManagementMenu.js
  agir/front/components/genericComponents/ObjectManagement/ManagementPanel.js
Labels: minor bug

#1276 chore: update NPM dependencies (minor updates)
  package-lock.json
  package.json
Labels: javascript, dependencies

#1277 fix: group page SecondaryActions style
  agir/groups/components/groupPage/GroupUserActions/SecondaryActions.js
  agir/groups/components/groupPage/GroupUserActions/SecondaryActions.stories.js
Labels: bug

#1289 Fix personform group field
  agir/people/person_forms/fields.py
Labels: bug

#1281 chore: update NPM dependencies (minor updates)
  .eslintrc.json
  package-lock.json
  package.json
Labels: javascript, dependencies

#1295 Update JoinGroupDialog content and never skip last step
  .hypothesis/examples/91e5a9523344ce8d/28fb31b68dc2df07
  .hypothesis/examples/91e5a9523344ce8d/4d6d9c72be1b6460
  .hypothesis/examples/91e5a9523344ce8d/57e81d7f88fc3215
  .hypothesis/examples/91e5a9523344ce8d/9542ea0811b8622b
  .hypothesis/examples/91e5a9523344ce8d/9b331023b20abedd
  .hypothesis/examples/91e5a9523344ce8d/b5799c1a1262dfa1
  .hypothesis/examples/91e5a9523344ce8d/bc165ba6d9998f87
  .hypothesis/examples/91e5a9523344ce8d/be3e4607b8377f6a
  .hypothesis/examples/91e5a9523344ce8d/eaed113a84d10df2
  .hypothesis/examples/91e5a9523344ce8d/f2a4a4d752b09b7b
  .hypothesis/examples/f39eb4bec40384d6/a87d6e002bd44896
  .hypothesis/examples/f39eb4bec40384d6/d8179209b48c433c
  agir/groups/components/groupPage/GroupUserActions/EditMembershipDialog.js
  agir/groups/components/groupPage/GroupUserActions/JoinGroupDialog.js
Labels: bug-staging

#1298 fix: replace event required doc template files with urls
  agir/events/components/eventRequiredDocuments/config.js
  agir/front/static/front/modeles/Attestation_concours_en_nature.pdf
  agir/front/static/front/modeles/Attestation_mise_a_disposition_etablissement.pdf
  agir/front/static/front/modeles/Attestation_salle_municipale.pdf
Labels: bug, Quickfix

#1318 Try to fix python black version conflict in gh workflow
  .github/workflows/run-tests.yml
Labels: bug-staging

#1312 Fix extra comma causing crash on profile/payment page with LFI monthly donation
  .hypothesis/examples/05ae5a533c0b69a4/cfe9a7d7af53c028
  .hypothesis/examples/6e8be5e69c554c1f/c67f2678da960427
  .hypothesis/examples/7416a4d6aaca03fd/197142b80a3ca7a7
  .hypothesis/examples/7416a4d6aaca03fd/2172e35f3eb709d1
  .hypothesis/examples/7416a4d6aaca03fd/3b47249486cd788e
  .hypothesis/examples/7416a4d6aaca03fd/442388d9703e2c58
  .hypothesis/examples/7416a4d6aaca03fd/7e7841492312774b
  .hypothesis/examples/7416a4d6aaca03fd/9f09c5afc379855e
  .hypothesis/examples/7416a4d6aaca03fd/c1cfd64283b028ee
  .hypothesis/examples/7416a4d6aaca03fd/efc7b342e1f51195
  .hypothesis/examples/7416a4d6aaca03fd/f0dedc131ab1cfcc
  .hypothesis/examples/7416a4d6aaca03fd/f9fd2724471b00cb
  .hypothesis/examples/91e5a9523344ce8d/03b67a7ea396fd00
  .hypothesis/examples/91e5a9523344ce8d/46dc50db0142d9e4
  .hypothesis/examples/91e5a9523344ce8d/51640a68755119ab
  .hypothesis/examples/91e5a9523344ce8d/562ea379c899eaeb
  .hypothesis/examples/91e5a9523344ce8d/64a567cbf86bfbf6
  .hypothesis/examples/91e5a9523344ce8d/79cdcccd7537a272
  .hypothesis/examples/91e5a9523344ce8d/b6b1323623a15dbf
  .hypothesis/examples/91e5a9523344ce8d/be3e4607b8377f6a
  .hypothesis/examples/91e5a9523344ce8d/cf53ca263c5fee49
  .hypothesis/examples/91e5a9523344ce8d/e409417fe0233d25
  .hypothesis/examples/943cbc05f4a80c6b/4b432cb5a3a366bb
  .hypothesis/examples/943cbc05f4a80c6b/50c6d5df1a8e427a
  .hypothesis/examples/943cbc05f4a80c6b/55ec096facf7f5b0
  .hypothesis/examples/943cbc05f4a80c6b/6bd00346852120e7
  .hypothesis/examples/943cbc05f4a80c6b/9443a7685e13b53b
  .hypothesis/examples/943cbc05f4a80c6b/b4039bd57b65d5fe
  .hypothesis/examples/943cbc05f4a80c6b/ccad96f8338dd73b
  .hypothesis/examples/b9d64d99186294e7/347bd000a73fdb74
  .hypothesis/examples/b9d64d99186294e7/ccad96f8338dd73b
  .hypothesis/examples/f39eb4bec40384d6/e203e0d5992c7615
  agir/donations/apps.py
Labels: bug, Quickfix

#1325 Fix: scrollToError broke when error is null
  agir/front/components/app/utils.js
Labels: bug-staging

#1313 chore: update NPM dependencies (minor updates)
  package-lock.json
  package.json
Labels: javascript, dependencies, do not merge, wait next release

#1334 Donations : fix reverse url replaced
  agir/donations/serializers.py
  agir/front/components/app/routes.config.js
  agir/front/urls.py
Labels: bug-staging

#1340 Revert "Add image-from-URL block to jlm2022 mosaico template"
  .hypothesis/examples/6f17816d3eb35872/4be04eceea3f8c33
  .hypothesis/examples/6f17816d3eb35872/8cdfd9f0edf92a42
  .hypothesis/examples/80fbecba29df1522/004443e70e8ee7b3
  .hypothesis/examples/91e5a9523344ce8d/0036941949f1bf87
  .hypothesis/examples/91e5a9523344ce8d/012616dc5ea07c92
  .hypothesis/examples/91e5a9523344ce8d/03215bdaef96ca5c
  .hypothesis/examples/91e5a9523344ce8d/09ad596f5720e0e8
  .hypothesis/examples/91e5a9523344ce8d/23bd4e004f8a7e73
  .hypothesis/examples/91e5a9523344ce8d/35d367b121c97fcb
  .hypothesis/examples/91e5a9523344ce8d/3a0e0da79c059baa
  .hypothesis/examples/91e5a9523344ce8d/495d54f7effe90cb
  .hypothesis/examples/91e5a9523344ce8d/4c11691b40c42168
  .hypothesis/examples/91e5a9523344ce8d/620421a2272ee45d
  .hypothesis/examples/91e5a9523344ce8d/8a45051dd3ef1544
  .hypothesis/examples/91e5a9523344ce8d/8bbfd7e1bb74c379
  .hypothesis/examples/91e5a9523344ce8d/8dfc4c697e40cc67
  .hypothesis/examples/91e5a9523344ce8d/90f3e23a9c7dd52c
  .hypothesis/examples/91e5a9523344ce8d/98f743803fb8819f
  .hypothesis/examples/91e5a9523344ce8d/a8881bd4d72e83ea
  .hypothesis/examples/91e5a9523344ce8d/b0471b77b42372c2
  .hypothesis/examples/91e5a9523344ce8d/d459db9c1b3a09f1
  .hypothesis/examples/91e5a9523344ce8d/dd0336d9d1417759
  .hypothesis/examples/91e5a9523344ce8d/e02c22875db5fc89
  .hypothesis/examples/91e5a9523344ce8d/e52488f6f156dab8
  .hypothesis/examples/91e5a9523344ce8d/e7add6df10f5028c
  .hypothesis/examples/91e5a9523344ce8d/f1fa66410f084b4f
  .hypothesis/examples/91e5a9523344ce8d/f48ec11e93736e9e
  .hypothesis/examples/91e5a9523344ce8d/f5453ce5c9305ee6
  .hypothesis/examples/91e5a9523344ce8d/f6aef7c121feade3
  .hypothesis/examples/b48bda71ee0ad32b/43bf235cfa7eb6fa
  .hypothesis/examples/b9d64d99186294e7/1c03cd5479b3d650
  .hypothesis/examples/f39eb4bec40384d6/0c6559a6652ab77e
  agir/mailing/actions.py
  agir/mailing/static/mosaico_templates/versafix-jlm2022/edres/imageURLBlock.png
  agir/mailing/static/mosaico_templates/versafix-jlm2022/edres/melenchon2022LogoBlock.png
  agir/mailing/static/mosaico_templates/versafix-jlm2022/template.html
  agir/people/views/form.py
Labels: bug-staging

#1332 Update people.person search field DB trigger functions
  .hypothesis/examples/05ae5a533c0b69a4/732771c2ef170931
  .hypothesis/examples/05ae5a533c0b69a4/8b74e0d98b8fd045
  .hypothesis/examples/05ae5a533c0b69a4/c37ebdbed5f9de4f
  .hypothesis/examples/6e8be5e69c554c1f/505c06f0efb1e294
  .hypothesis/examples/6f17816d3eb35872/904f619b4371c9df
  .hypothesis/examples/91e5a9523344ce8d/0036941949f1bf87
  .hypothesis/examples/91e5a9523344ce8d/012616dc5ea07c92
  .hypothesis/examples/91e5a9523344ce8d/03215bdaef96ca5c
  .hypothesis/examples/91e5a9523344ce8d/09ad596f5720e0e8
  .hypothesis/examples/91e5a9523344ce8d/495d54f7effe90cb
  .hypothesis/examples/91e5a9523344ce8d/620421a2272ee45d
  .hypothesis/examples/91e5a9523344ce8d/8a45051dd3ef1544
  .hypothesis/examples/91e5a9523344ce8d/8dfc4c697e40cc67
  .hypothesis/examples/91e5a9523344ce8d/90f3e23a9c7dd52c
  .hypothesis/examples/91e5a9523344ce8d/98f743803fb8819f
  .hypothesis/examples/91e5a9523344ce8d/a8881bd4d72e83ea
  .hypothesis/examples/91e5a9523344ce8d/b0471b77b42372c2
  .hypothesis/examples/91e5a9523344ce8d/d459db9c1b3a09f1
  .hypothesis/examples/91e5a9523344ce8d/dd0336d9d1417759
  .hypothesis/examples/91e5a9523344ce8d/e02c22875db5fc89
  .hypothesis/examples/91e5a9523344ce8d/e52488f6f156dab8
  .hypothesis/examples/91e5a9523344ce8d/f1fa66410f084b4f
  .hypothesis/examples/91e5a9523344ce8d/f48ec11e93736e9e
  .hypothesis/examples/91e5a9523344ce8d/f5453ce5c9305ee6
  .hypothesis/examples/91e5a9523344ce8d/f6aef7c121feade3
  .hypothesis/examples/b48bda71ee0ad32b/35aa1bd3ae324685
  .hypothesis/examples/f39eb4bec40384d6/5ed9fe73b26bb65b
  .hypothesis/examples/f39eb4bec40384d6/945fa01d1d6fc1f9
  agir/people/migrations/0001_creer_modeles.py
  agir/people/migrations/0009_update_person_trigger_functions.py
  agir/people/tests/test_actions.py
Labels: bug, do not merge, wait next release

#1371 Donations fixes : direct payment with user unknown
  agir/donations/serializers.py
  agir/donations/tests/test_donations_usecases.py
  agir/donations/views/api_views.py
  agir/payments/actions/payments.py
Labels: bug-staging

#1373 Donations : create person when user unknown
  .hypothesis/examples/6f17816d3eb35872/7849587a3e4d2261
  .hypothesis/examples/91e5a9523344ce8d/23bd4e004f8a7e73
  .hypothesis/examples/91e5a9523344ce8d/4c11691b40c42168
  agir/donations/tests/test_donations_usecases.py
  agir/donations/views/api_views.py
  agir/payments/actions/payments.py
Labels: bug-staging

#1349 Fix DateTimeField dropdown position on small screens
  agir/front/components/formComponents/DateTimeField.js
Labels: do not merge, wait next release, minor bug

#1356 Fix font sizes (by using pxs instead of rems) of mobile navigation elements
  agir/events/components/common/UpcomingEvents/MiniEventCard.js
  agir/front/components/app/ActionButtons.js
  agir/front/components/app/Navigation/BottomBar/BottomBar.js
  agir/front/components/app/Navigation/TopBar/MobileNavBar/DashboardPageBar.js
  agir/front/components/app/Navigation/TopBar/MobileNavBar/RightLink.js
  agir/front/components/app/Navigation/TopBar/MobileNavBar/SecondaryPageBar.js
  agir/front/components/app/Navigation/TopBar/MobileNavBar/StyledBar.js
Labels: do not merge, wait next release, minor bug

#1294 Style groups page and reset mobile titles
  agir/front/components/app/routes.config.js
  agir/groups/components/groupsPage/UserGroups.js
Labels: wait next release, minor bug

#1305 Position button loader to avoid scroll
  agir/front/components/genericComponents/Button/BaseButton.js
Labels: wait next release, minor bug

#1376 Fix push subscription error
  agir/notifications/components/push/api.js
  agir/notifications/components/push/subscriptions.js
Labels: bug-staging

#1375 Refresh group page personalInfoConsent after update
  agir/front/components/ActionToolsPage/ActionTools.js
  agir/groups/components/groupPage/GroupUserActions/EditMembershipDialog.js
  agir/groups/components/groupPage/GroupUserActions/JoinGroupDialog.js
  agir/groups/components/groupPage/GroupUserActions/index.js
  agir/groups/components/groupsPage/UserGroups.js
Labels: bug

#1377 ActionButtons and ActionToolsPage various fixes
  .hypothesis/examples/5b721dd590d22e25/e4736759ff3ad786
  .hypothesis/examples/6e8be5e69c554c1f/d9210e63b36af302
  .hypothesis/examples/6f17816d3eb35872/0ad04be846153693
  .hypothesis/examples/6f17816d3eb35872/bf97268760c5e504
  .hypothesis/examples/8c5cf6277a8ac235/baaa730b1f63d06d
  .hypothesis/examples/b48bda71ee0ad32b/a5473c4f80829fb9
  .hypothesis/examples/f39eb4bec40384d6/1a97d3752a9e809a
  .hypothesis/examples/f39eb4bec40384d6/71be92cfee5823b3
  agir/authentication/serializers.py
  agir/front/components/ActionToolsPage/MobileActionToolsPage.js
  agir/front/components/app/ActionButtons/ActionButtons.js
  agir/front/components/app/ActionButtons/actions.config.js
  agir/front/components/app/Navigation/navigation.config.json
  agir/front/components/app/routes.config.js
  agir/front/components/globalContext/nonReactRoutes.config.json
  agir/front/components/serviceWorker/cachedRoutes.config.js
Labels: bug-staging

#1378 Styles : group page padding
  agir/groups/components/groupsPage/GroupsPage.js
  agir/groups/components/groupsPage/UserGroups.js
Labels: minor bug

#1382 Donations fix: allow full page access for monthly donations
  agir/donations/components/donationPage/InformationsPage.js
  agir/donations/tasks.py
  agir/front/components/app/routes.config.js
  agir/front/urls.py
Labels: bug

#1384 Donations fixes: full page informations
  agir/donations/components/donationPage/InformationsPage.js
  agir/donations/views/api_views.py
Labels: bug-staging

#1385 Update `materiel` URL to `materiel.actionpopulaire.fr`
  agir/authentication/serializers.py
  agir/front/components/mockData/routes.json
  agir/groups/serializers.py
  agir/people/templates/people/profile/volunteer.html
Labels: do not merge, wait next release, minor bug

#1387 Update onboarding images + remove `thematic` onboarding
  agir/front/components/genericComponents/Onboarding.js
  agir/front/components/genericComponents/images/onboarding__action.jpg
  agir/front/components/genericComponents/images/onboarding__event.jpg
  agir/front/components/genericComponents/images/onboarding__thematic.jpg
Labels: do not merge, wait next release

#1383 Fix typo in dashboard desktop layout aside title
  agir/front/components/app/Layout/DesktopLayout.js
Labels: bug

#1386 Fix event og:image date format
  agir/events/views/event_views.py
Labels: do not merge, wait next release, minor bug

#1370 Keyboard navigation fixes
  agir/events/components/agendaPage/EventSuggestions.js
  agir/front/components/app/Navigation/TopBar/DesktopNavBar/RightLinks.js
  agir/front/components/genericComponents/FilterTabs.js
  agir/front/components/genericComponents/FilterTabs.stories.js
  agir/front/components/genericComponents/Modal.js
  agir/front/components/genericComponents/Popin.js
  agir/lib/components/utils/hooks.js
Labels: minor bug

#1379 Fix create AP-dedicated 2022 donation endpoint
  .hypothesis/examples/6f17816d3eb35872/1917a59f48afa18e
  .hypothesis/examples/f39eb4bec40384d6/ec192f4b94059256
  agir/front/components/ActionToolsPage/ActionToolsPage.js
  agir/front/components/ActionToolsPage/DonateCard.js
  agir/front/components/app/ActionButtons/ActionButtons.js
  agir/front/components/serviceWorker/cachedRoutes.config.js
  agir/presidentielle2022/actions.py
  agir/presidentielle2022/tests.py
  agir/presidentielle2022/urls.py
  agir/presidentielle2022/views.py
Labels: bug-staging

#1388 Allow exporting person list from admin (max 500 lines)
  .hypothesis/examples/05ae5a533c0b69a4/905718e2ce771764
  .hypothesis/examples/6e8be5e69c554c1f/ccc53ff6390fde44
  .hypothesis/examples/80fbecba29df1522/b4d69e8c7ba67773
  .hypothesis/examples/b48bda71ee0ad32b/710f131eeacfc51e
  .hypothesis/examples/b48bda71ee0ad32b/87571ad30a34ebfb
  .hypothesis/examples/b9d64d99186294e7/064e719512eab93f
  .hypothesis/examples/b9d64d99186294e7/0c970fa7e26c6236
  agir/people/actions/export.py
  agir/people/admin/actions.py
  agir/people/admin/panels.py
  agir/people/migrations/0011_add_export_people_person_permission.py
  agir/people/models.py
Labels: do not merge, wait next release

#1350 Fix `UploadEventImageView` broken permissions
  .hypothesis/examples/6e8be5e69c554c1f/59e5f64e46ced237
  .hypothesis/examples/6e8be5e69c554c1f/b3795aa1a7f14d0f
  .hypothesis/examples/6f17816d3eb35872/4e5a5a1f3f331e99
  .hypothesis/examples/6f17816d3eb35872/dc675589aea96917
  .hypothesis/examples/6f17816d3eb35872/f1cbfdf7333d5189
  .hypothesis/examples/b9d64d99186294e7/9d365df4e83555b7
  .hypothesis/examples/b9d64d99186294e7/bd89d5dd5c3f041c
  .hypothesis/examples/b9d64d99186294e7/cadd4c80081b34d1
  .hypothesis/examples/b9d64d99186294e7/da5accd581da80e2
  .hypothesis/examples/f39eb4bec40384d6/485aa6da16768de3
  agir/events/rules.py
  agir/events/tests/test_views.py
  agir/events/views/event_views.py
Labels: minor bug

#1374 Fix missing import in agir/msgs/models
  .hypothesis/examples/f39eb4bec40384d6/a35f8289d1516d78
  .hypothesis/examples/f39eb4bec40384d6/dd6f10047cd046d1
  agir/msgs/models.py
Labels: minor bug
