Repository lafranceinsoumise/actionpopulaire.fr, pull requests merged in 2022-05, with the labels that each got.

#2104 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#2107 Fix buttonLineBlock in jlm2022 mosaico template
  agir/mailing/static/mosaico_templates/versafix-jlm2022/template.html
Labels: minor bug

#2114 Fix jlm2022 mailing template button line block 3-buttons line-height
  .hypothesis/examples/5b721dd590d22e25/9f1aaabf9d9a2ba8
  .hypothesis/examples/6e8be5e69c554c1f/eebb95a12d87d2dd
  .hypothesis/examples/a8f3af75ba35d1d2/c1d01e2b912469b9
  .hypothesis/examples/f3043d07df515730/6250a6331bd9063c
  agir/mailing/static/mosaico_templates/versafix-jlm2022/template.html
Labels: bug-staging

#2119 Fix unhandled celery errors
  .hypothesis/examples/6e8be5e69c554c1f/1a630e9b34ac919e
  .hypothesis/examples/6e8be5e69c554c1f/9e2efe78d1445fba
  .hypothesis/examples/df274aa83beb1e49/b72737a01ba329b9
  agir/lib/celery.py
  agir/notifications/tasks.py
  agir/voting_proxies/tasks.py
  agir/voting_proxies/tests/test_tasks.py
Labels: minor bug

#2120 fix: EventRequiredDocumentsPage without projectId crash + redirect loop
  .hypothesis/examples/a8f3af75ba35d1d2/35864cb11c0971ad
  .hypothesis/examples/e3879ab8af5e6fa2/8258e732f0c3e777
  agir/events/components/eventRequiredDocuments/EventRequiredDocumentsPage.js
  agir/front/views.py
Labels: bug-staging

#2122 Limit event download-only document page access to event organizers
  agir/events/components/eventRequiredDocuments/EventRequiredDocumentsPage.js
Labels: bug-staging

#2124 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#2063 Refactor: SearchCountryField component
  agir/front/components/formComponents/CountryField.js
  agir/front/components/formComponents/SelectField.js
Labels: feature

#2138 Revert "Merge pull request #2131 from lafranceinsoumise/dependabot/pip/social-auth-core-4.2.0"
  poetry.lock
  pyproject.toml
Labels: bug

#2140 Apply per type group creation limit to referents and not to managers
  .hypothesis/examples/a8f3af75ba35d1d2/b6b9829f99382b04
  .hypothesis/examples/ddb76f4f03fab698/f6be34c3ad30ded3
  agir/events/components/createEventPage/EventForm/EventImageField.js
  agir/groups/views/management_views.py
Labels: bug

#2141 Fix vpr proxy information api view permissions
  .hypothesis/examples/6e8be5e69c554c1f/f4b6d79fe0b88059
  agir/voting_proxies/views.py
Labels: bug

#2153 chore: update NPM dependencies
  package-lock.json
  package.json
  webpack.common.js
Labels: javascript, dependencies

#2156 Fix 500 error on event image upload with validation errors
  .hypothesis/examples/020872f66051c7bb/a929bad6c5dba2d6
  agir/events/views/event_views.py
Labels: minor bug

#2157 fix: exclude unpublished groups from exclusivity certification criterium check
  .hypothesis/examples/020872f66051c7bb/a929bad6c5dba2d6
  .hypothesis/examples/a8f3af75ba35d1d2/e76666560862ae13
  .hypothesis/examples/f3043d07df515730/8b1d657678b791fb
  agir/groups/models.py
Labels: Quickfix
