Repository lafranceinsoumise/actionpopulaire.fr, pull requests merged in 2022-03, with the labels that each got.

#1838 Transfer sender email template member list
  .hypothesis/examples/b9d64d99186294e7/1b0d7e7e9b56fe71
  .hypothesis/examples/f3043d07df515730/6029f02d84398351
  agir/groups/actions/transfer.py
  agir/lib/templates/mail_templates/TRANSFER_SENDER.html
  agir/lib/templates/mail_templates/TRANSFER_SENDER.txt
Labels: minor bug

#1832 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1841 AuthenticatedLogin - redirect if next param is present
  agir/front/components/authentication/Connexion/AuthenticatedLogin.js
Labels: bug-staging

#1817 Fix RightLink : add pathname to useMessageSWR
  agir/front/components/app/Navigation/TopBar/MobileNavBar/RightLink.js
  agir/front/components/app/utils.js
  agir/msgs/components/common/hooks.js
Labels: bug

#1845 Remove all .map files from sw cache list
  webpack.common.js
Labels: bug-staging

#1847 Add homepage link button to ErrorPage
  agir/front/components/errorPage/ErrorPage.js
Labels: bug-staging

#1848 Fix : reactivate mobile message options
  agir/front/components/app/Navigation/TopBar/MobileNavBar/RightLink.js
Labels: ready

#1855 Fix TRANSFER_RECEIVER email templates
  agir/api/settings.py
  agir/lib/templates/mail_templates/TRANSFER_RECEIVER.html
  agir/lib/templates/mail_templates/TRANSFER_RECEIVER.txt
Labels: minor bug

#1853 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1860 Send coorganization group member event notifications
  .hypothesis/examples/6e8be5e69c554c1f/cfd9ae742bd34ce7
  .hypothesis/examples/6f17816d3eb35872/1bf828c349ba964e
  .hypothesis/examples/a8f3af75ba35d1d2/c9d9376eabd6b4b7
  .hypothesis/examples/ddb76f4f03fab698/31f9184d3c1f2fbb
  agir/events/views/api_views.py
  agir/groups/tasks.py
  agir/groups/tests/test_tasks.py
Labels: bug-staging

#1862 Try to fix icalendar download link on iOS
  agir/events/components/eventPage/AddToCalendarWidget.js
Labels: minor bug

#1863 Try to reduce group suggestion API query time
  .hypothesis/examples/6e8be5e69c554c1f/9b4e524c11788257
  agir/groups/views/api_views.py
Labels: performance

#1867 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1864 Try to fix `ACTIONPOPULAIRE-KS`
  .hypothesis/examples/5b721dd590d22e25/cfbb827806d75c86
  .hypothesis/examples/6e8be5e69c554c1f/0a13a99b8efb9201
  .hypothesis/examples/a8f3af75ba35d1d2/dc95c8b3eb41b071
  agir/events/tests/test_api_views.py
  agir/lib/geo.py
  agir/voting_proxies/tests/test_views.py
Labels: minor bug

#1873 Fix toktok api cache settings
  agir/presidentielle2022/views.py
Labels: bug

#1871 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1872 Update webpack build
  agir/events/components/EventSettings/routes.config.js
  agir/front/components/app/Router.js
  agir/front/components/app/routes.components.js
  agir/front/components/app/routes.config.js
  agir/groups/components/groupPage/GroupSettings/routes.config.js
  package-lock.json
  package.json
  webpack.common.js
  webpack.dev.js
  webpack.production.js
Labels: performance

#1878 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1877 Fix : avoid loading two components for the homepage route
  agir/front/components/app/Router.js
  webpack.common.js
Labels: performance

#1879 feat: split biggest front dependencies into their own chunk for longer-term caching
  webpack.common.js
Labels: performance

#1846 Create fulfill_voting_proxy_requests command
  .hypothesis/examples/5b721dd590d22e25/07ff78464a24a87c
  .hypothesis/examples/5b721dd590d22e25/595275195026e7e6
  .hypothesis/examples/6e8be5e69c554c1f/4ad4c8410631ea0c
  .hypothesis/examples/6f17816d3eb35872/13aef60f2225b008
  .hypothesis/examples/a8f3af75ba35d1d2/1b2dbea5d165fdd7
  .hypothesis/examples/a8f3af75ba35d1d2/a3e6138469149d34
  .hypothesis/examples/a8f3af75ba35d1d2/ec56bb1987b19462
  .hypothesis/examples/b9d64d99186294e7/78360f41539ba717
  .hypothesis/examples/dd8c1e5b4eeb95d9/57982bf866c68bd3
  .hypothesis/examples/dd8c1e5b4eeb95d9/6ebefb5f2210d4bd
  .hypothesis/examples/dd8c1e5b4eeb95d9/e57eb57ef825747f
  .hypothesis/examples/ddb76f4f03fab698/2f8026437ecfccc5
  .hypothesis/examples/ddb76f4f03fab698/b58a401119198174
  .hypothesis/examples/df274aa83beb1e49/053d71a133dbf26a
  agir/api/settings.py
  agir/lib/templates/mail_templates/VOTING_PROXY_CANDIDATE_INVITATION.html
  agir/lib/templates/mail_templates/VOTING_PROXY_CANDIDATE_INVITATION.txt
  agir/voting_proxies/actions.py
  agir/voting_proxies/components/Common/api.js
  agir/voting_proxies/components/VotingProxy/NewVotingProxy/NewVotingProxy.js
  agir/voting_proxies/components/VotingProxy/NewVotingProxy/NewVotingProxySuccess.js
  agir/voting_proxies/components/VotingProxy/NewVotingProxy/VotingProxyForm.js
  agir/voting_proxies/management/commands/__init__.py
  agir/voting_proxies/management/commands/fulfill_voting_proxy_requests.py
  agir/voting_proxies/migrations/0003_votingproxy_last_matched.py
  agir/voting_proxies/models.py
  agir/voting_proxies/serializers.py
  agir/voting_proxies/tasks.py
  poetry.lock
  pyproject.toml
Labels: feature

#1893 Add search field to voting proxy admin list pages
  agir/voting_proxies/admin.py
Labels: feature

#1894 Add matching buttons to vpr admin page
  .hypothesis/examples/5b721dd590d22e25/74287dd62f4c4aac
  .hypothesis/examples/6e8be5e69c554c1f/d76b461f687d0510
  .hypothesis/examples/6f17816d3eb35872/c77c4d38839179dc
  agir/voting_proxies/actions.py
  agir/voting_proxies/admin/__init__.py
  agir/voting_proxies/admin/actions.py
  agir/voting_proxies/admin/panels.py
  agir/voting_proxies/management/commands/fulfill_voting_proxy_requests.py
Labels: feature

#1895 Fix fulfill_voting_proxy_requests script query
  agir/voting_proxies/actions.py
  agir/voting_proxies/tests/test_actions.py
Labels: feature, bug-staging

#1896 VPRs fixes
  .hypothesis/examples/5b721dd590d22e25/add912b9b09c15df
  .hypothesis/examples/5b721dd590d22e25/bc44568be20af8be
  .hypothesis/examples/6f17816d3eb35872/f50abc03475a9165
  .hypothesis/examples/a8f3af75ba35d1d2/221d970eebdf6ca9
  .hypothesis/examples/a8f3af75ba35d1d2/8e8d8fdd1c10c12d
  .hypothesis/examples/b9d64d99186294e7/c71ceb6ec7540144
  .hypothesis/examples/ddb76f4f03fab698/cf33fa2525349f7c
  .hypothesis/examples/df274aa83beb1e49/cf26553f6f291c9f
  .hypothesis/examples/f3043d07df515730/e1f44b06a455fb71
  agir/front/components/formComponents/TextField.js
  agir/voting_proxies/actions.py
  agir/voting_proxies/components/VotingProxy/NewVotingProxy/VotingProxyForm.js
  agir/voting_proxies/components/VotingProxy/NewVotingProxy/form.config.js
  agir/voting_proxies/components/VotingProxy/ReplyToVotingProxyRequests/ReplyToVotingProxyRequests.js
  agir/voting_proxies/components/VotingProxy/ReplyToVotingProxyRequests/ReplyingForm.js
  agir/voting_proxies/components/VotingProxyRequest/NewVotingProxyRequest/VotingProxyRequestForm.js
  agir/voting_proxies/serializers.py
  agir/voting_proxies/tests/test_actions.py
  agir/voting_proxies/tests/test_views.py
  agir/voting_proxies/views.py
Labels: feature, bug-staging

#1903 Fix missing global error on new voting proxy request form
  agir/voting_proxies/components/VotingProxyRequest/NewVotingProxyRequest/NewVotingProxyRequest.js
  agir/voting_proxies/components/VotingProxyRequest/NewVotingProxyRequest/NewVotingProxyRequestHowTo.js
  agir/voting_proxies/components/VotingProxyRequest/NewVotingProxyRequest/NewVotingProxyRequestIntro.js
  agir/voting_proxies/components/VotingProxyRequest/NewVotingProxyRequest/VotingProxyRequestForm.js
Labels: feature, bug-staging

#1904 Voting proxy request confirmation - add confirmation modal
  agir/front/components/genericComponents/ModalConfirmation.js
  agir/voting_proxies/components/VotingProxyRequest/VotingProxyRequestDetails/VotingProxyWidget.js
Labels: feature, bug-staging

#1908 Fix voting proxy request SMS encoding
  agir/lib/sms.py
  agir/voting_proxies/models.py
  agir/voting_proxies/tasks.py
Labels: feature, bug-staging

#1905 Fix: group events duplicates
  agir/groups/views/api_views.py
Labels: minor bug

#1910 Remove useless api calls
  agir/activity/components/common/hooks.js
  agir/front/components/app/Navigation/TopBar/MobileNavBar/RightLink.js
  agir/front/components/app/routes.config.js
  agir/groups/components/groupPage/GroupMessagePage/index.js
  agir/msgs/components/MessagePage/MessagePage.js
Labels: performance

#1915 Update GitHub actions webpack-build workflow
  .github/workflows/run-tests.yml
  .github/workflows/webpack-build.yml
Labels: bug

#1917 Remove clean webpack plugin
  package-lock.json
  package.json
  webpack.common.js
Labels: bug

#1918 Fix missing report prop + send dry-run report email
  agir/voting_proxies/management/commands/fulfill_voting_proxy_requests.py
  agir/voting_proxies/tasks.py
Labels: bug

#1919 Add tqdm to fulfill_voting_proxy_requests command
  agir/voting_proxies/management/commands/fulfill_voting_proxy_requests.py
Labels: Quickfix

#1920 Try to reduce get_voting_proxy_requests_for_proxy geo query time
  agir/voting_proxies/actions.py
Labels: Quickfix

#1921 Try to improve `match_available_proxies_with_requests` query time
  .hypothesis/examples/6f17816d3eb35872/12bcbef758d37278
  .hypothesis/examples/df274aa83beb1e49/1b72bea22d527242
  agir/voting_proxies/actions.py
  agir/voting_proxies/management/commands/fulfill_voting_proxy_requests.py
Labels: performance, Quickfix

#1922 Remove linebreaks from vpr script report json file content
  agir/voting_proxies/tasks.py
Labels: Quickfix

#1924 Set missing autocomplete fields on vp and vpr admin change pages
  .hypothesis/examples/b9d64d99186294e7/badf91d2c5d43a80
  .hypothesis/examples/df274aa83beb1e49/accb9f4fc504f68a
  agir/voting_proxies/admin/panels.py
Labels: bug, Quickfix

#1926 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1923 Fix vpr script invitation queries
  .hypothesis/examples/df274aa83beb1e49/ef8e6836f0460ae6
  agir/voting_proxies/actions.py
  agir/voting_proxies/tests/test_actions.py
Labels: Quickfix

#1927 Settings panels : fix save button overlapping panelWrapper
  agir/front/components/genericComponents/ObjectManagement/ManagementPanel.js
  agir/front/components/genericComponents/ObjectManagement/PanelWrapper.js
Labels: minor bug

#1929 Fix staging package-lock.json
  package-lock.json
Labels: bug-staging

#1932 Groups cards styles
  agir/events/components/eventPage/DesktopEventPage.js
  agir/events/components/eventPage/MobileEventPage.js
  agir/groups/components/groupComponents/GroupsCard.js
  agir/groups/serializers.py
Labels: feature

#1934 Group participants: fixes
  agir/events/components/EventSettings/EventParticipants.js
  agir/events/components/EventSettings/GroupItem.js
  agir/events/components/eventPage/AddGroupAttendee.js
  agir/events/components/eventPage/DesktopEventPage.js
  agir/events/components/eventPage/EventHeader.js
  agir/events/components/eventPage/JoiningDetails.js
  agir/events/components/eventPage/MobileEventPage.js
  agir/events/views/api_views.py
  agir/front/components/genericComponents/EventGroupsAttendees.js
Labels: bug-staging

#1935 Widen group coorganisation group suggestions
  .hypothesis/examples/6a2e6cafece44878/a1adcc6fb7379717
  .hypothesis/examples/6a2e6cafece44878/e6655d41a7f56bb3
  .hypothesis/examples/95dc7b7ff0e493cd/0107fb59171bead9
  .hypothesis/examples/95dc7b7ff0e493cd/518fe4d9b3890478
  .hypothesis/examples/95dc7b7ff0e493cd/763d30f27d6b1841
  .hypothesis/examples/95dc7b7ff0e493cd/ad072b419cb552e8
  .hypothesis/examples/95dc7b7ff0e493cd/dc5455a33e96e60e
  .hypothesis/examples/95dc7b7ff0e493cd/deae3ba5fa216529
  .hypothesis/examples/e3879ab8af5e6fa2/035b4e184a9ecfd4
  .hypothesis/examples/e3879ab8af5e6fa2/ee7d5d9c7fe16fc0
  .hypothesis/examples/f3043d07df515730/5c10ecd706447478
  agir/events/views/api_views.py
Labels: bug-staging

#1928 Add explanation text to ReplyToVotingProxyRequests form
  agir/voting_proxies/actions.py
  agir/voting_proxies/components/VotingProxy/ReplyToVotingProxyRequests/ReplyingForm.js
  agir/voting_proxies/models.py
  agir/voting_proxies/tasks.py
Labels: bug, feature

#1940 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1942 Fix group participants : show groups attendees for managers
  agir/events/components/eventPage/EventHeader.js
  agir/events/components/eventPage/JoiningDetails.js
Labels: bug-staging

#1950 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1943 Try to limit find_voting_proxy_candidates_for_requests queries
  .hypothesis/examples/5b721dd590d22e25/89fc7aac89cc138f
  .hypothesis/examples/6a2e6cafece44878/6c1577c7d5e82d51
  .hypothesis/examples/95dc7b7ff0e493cd/70d67bad3fb5f1c0
  .hypothesis/examples/95dc7b7ff0e493cd/7d6b3dfea8d0aa6c
  agir/voting_proxies/actions.py
Labels: feature, performance

#1945 Restore group coorganization MAX_RESULTS and remove suggestion limit
  agir/events/components/EventSettings/Organization/AddGroupOrganizer.js
Labels: bug

#1955 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1957 Restore missing zip property in updateProfile api helper
  agir/front/components/authentication/Connexion/TellMore/TellMore.js
  agir/front/components/authentication/api.js
Labels: bug

#1936 Send voting proxy request messages as emails
  .hypothesis/examples/5b721dd590d22e25/ac8df60c52eca932
  .hypothesis/examples/5b721dd590d22e25/d5ae82e1cec2f823
  .hypothesis/examples/6a2e6cafece44878/1c11ce733746fe9d
  .hypothesis/examples/6a2e6cafece44878/8fe1d9485f2f97d1
  .hypothesis/examples/6a2e6cafece44878/bc659ea68629faff
  .hypothesis/examples/6a2e6cafece44878/fcc3c69a59a619a6
  .hypothesis/examples/6e8be5e69c554c1f/eb17f02b6501ad2b
  .hypothesis/examples/95dc7b7ff0e493cd/0d5cc1b757dee999
  .hypothesis/examples/95dc7b7ff0e493cd/dc547870688dfe53
  .hypothesis/examples/a8f3af75ba35d1d2/0b344992e544cdcb
  .hypothesis/examples/a8f3af75ba35d1d2/2ebaab44d096439e
  .hypothesis/examples/a8f3af75ba35d1d2/7a0d23e300f5938a
  .hypothesis/examples/a8f3af75ba35d1d2/81a85cc72523f395
  .hypothesis/examples/a8f3af75ba35d1d2/9fedd9d9f1ff295f
  .hypothesis/examples/ddb76f4f03fab698/1b07751728f77c15
  .hypothesis/examples/ddb76f4f03fab698/a366f2e92bdb82e0
  .hypothesis/examples/e3879ab8af5e6fa2/0df4d090f4a3f06b
  .hypothesis/examples/e3879ab8af5e6fa2/2b8cf2d2dd28a3c5
  .hypothesis/examples/e3879ab8af5e6fa2/3835865aed00ee45
  .hypothesis/examples/e3879ab8af5e6fa2/53d01d01bcf061e1
  .hypothesis/examples/e3879ab8af5e6fa2/548585ecfd3e448b
  .hypothesis/examples/e3879ab8af5e6fa2/a1a1d6bce2ec1803
  .hypothesis/examples/e3879ab8af5e6fa2/acfad953d18c4510
  .hypothesis/examples/e3879ab8af5e6fa2/efe1bf79ccf7a831
  .hypothesis/examples/f3043d07df515730/f1e6393571863daa
  agir/api/settings.py
  agir/lib/templates/mail_templates/VOTING_PROXY_REQUEST_EMAIL.html
  agir/lib/templates/mail_templates/VOTING_PROXY_REQUEST_EMAIL.txt
  agir/voting_proxies/components/VotingProxyRequest/VotingProxyRequestDetails/VotingProxyRequestDetails.js
  agir/voting_proxies/components/VotingProxyRequest/VotingProxyRequestDetails/VotingProxyWidget.js
  agir/voting_proxies/models.py
  agir/voting_proxies/tasks.py
Labels: feature

#1956 Add voting proxy stats to weekly stats
  .hypothesis/examples/5b721dd590d22e25/efd6a3557f03a1a2
  .hypothesis/examples/ddb76f4f03fab698/f4e3b251355fc3df
  .hypothesis/examples/df274aa83beb1e49/366a941555076465
  agir/lib/management/commands/weekly_stats.py
  agir/lib/stats.py
Labels: feature

#1963 Always limit event suggestions api results + fix auto geolocalisation
  .hypothesis/examples/6e8be5e69c554c1f/0424d8934dbc38d3
  agir/events/views/api_views.py
Labels: minor bug

#1964 Fix geocode with data_france location field priority
  .hypothesis/examples/95dc7b7ff0e493cd/2daf46ae4a12f4e9
  .hypothesis/examples/e3879ab8af5e6fa2/62ce87e4bd8604ac
  agir/lib/geo.py
  agir/lib/tasks.py
  agir/people/admin/panels.py
Labels: minor bug

#1969 Fix useCustomAnnouncement loading state
  agir/activity/components/common/hooks.js
Labels: minor bug

#1966 Increase vpr fulfillment frequency + auto disable past voting dates
  .hypothesis/examples/5b721dd590d22e25/63d5733dc3f8ca43
  .hypothesis/examples/5b721dd590d22e25/8845a9dff65c650d
  .hypothesis/examples/5b721dd590d22e25/9c718edafdb45be4
  .hypothesis/examples/a8f3af75ba35d1d2/3c8283428b3b2120
  .hypothesis/examples/a8f3af75ba35d1d2/a27fb848b94bdefe
  .hypothesis/examples/e3879ab8af5e6fa2/7f3ddad5518d9b3e
  .hypothesis/examples/e3879ab8af5e6fa2/926743896e98c1b0
  .hypothesis/examples/e3879ab8af5e6fa2/d48e8fb5ff01639a
  agir/voting_proxies/actions.py
  agir/voting_proxies/admin/panels.py
  agir/voting_proxies/management/commands/fulfill_voting_proxy_requests.py
  agir/voting_proxies/models.py
Labels: feature

#1979 Fix broken activity 0029 migration
  agir/activity/migrations/0029_auto_20220307_1146.py
Labels: Quickfix

#1977 Update black to v22.3.0
  .github/workflows/run-tests.yml
  .hypothesis/examples/5b721dd590d22e25/3d2abd3d9c7082cc
  .hypothesis/examples/6a2e6cafece44878/697aba0c63e55496
  .hypothesis/examples/df274aa83beb1e49/224ea523e3f394c9
  agir/activity/migrations/0029_auto_20220307_1146.py
  agir/elus/serializers.py
  agir/groups/utils.py
  agir/lib/celery.py
  poetry.lock
  pyproject.toml
Labels: feature

#1975 `Fulfill_voting_proxy_requests` : send invitations for matched and unmatched requests
  agir/voting_proxies/management/commands/fulfill_voting_proxy_requests.py
Labels: feature

#1980 Fix UserMenu padding, add person city and update UpdateAddressModal text
  agir/front/components/allPages/PushModal/UpdateAddressModal.js
  agir/front/components/app/Navigation/TopBar/UserMenu.js
Labels: bug-staging

#1978 Search pages : add country filter on events & groups
  agir/front/api_views.py
  agir/front/components/SearchPage/SearchPage.js
  agir/front/components/SearchPage/useSearch.js
  agir/front/components/genericComponents/Tabs.js
Labels: feature

#1976 Voting proxy request confirmation reminder script
  agir/voting_proxies/management/commands/send_voting_proxy_confirmation_reminder.py
  agir/voting_proxies/models.py
  agir/voting_proxies/tasks.py
Labels: feature

#1981 Fix sentry 3038 + 3034 : undefined user groups
  agir/events/components/eventPage/AddGroupAttendee.js
  agir/events/components/eventPage/DesktopEventPage.js
  agir/events/components/eventPage/MobileEventPage.js
Labels: bug-staging

#1989 Fix event page join-as-group button width on small screens
  agir/events/components/eventPage/AddGroupAttendee.js
Labels: minor bug

#1988 Fix front : sentry 3058
  agir/events/components/eventPage/DesktopEventPage.js
  agir/events/components/eventPage/MobileEventPage.js
  agir/front/components/genericComponents/EventGroupsAttendees.js
Labels: minor bug

#1990 Fix sentry 3077
  agir/events/views/api_views.py
Labels: do not merge, minor bug

#1987 UserMessageView authentication/permission handling
  .hypothesis/examples/6a2e6cafece44878/93f5efa32e27db53
  .hypothesis/examples/a1f46b975a32cf3a/1f41f8b782a660dc
  .hypothesis/examples/a1f46b975a32cf3a/3a4116f3221d735d
  .hypothesis/examples/a1f46b975a32cf3a/761ace0f7636b38c
  .hypothesis/examples/a1f46b975a32cf3a/fabf7eeb12409a9f
  .hypothesis/examples/d1328b2e3da390fc/793c6db486c1a037
  .hypothesis/examples/d1328b2e3da390fc/af8f4cbdb8297048
  .hypothesis/examples/e3879ab8af5e6fa2/a3a87a07aeb4a293
  agir/front/views.py
Labels: minor bug

#1994 Revert "chore: modifications suite à mise à jour black"
  agir/elus/serializers.py
  agir/groups/utils.py
  agir/lib/celery.py
Labels: bug-staging

#1991 Voting proxy request fixes
  .hypothesis/examples/6a2e6cafece44878/eecf08ede4dcc2b3
  .hypothesis/examples/a1f46b975a32cf3a/1f41f8b782a660dc
  .hypothesis/examples/a1f46b975a32cf3a/761ace0f7636b38c
  .hypothesis/examples/a1f46b975a32cf3a/fabf7eeb12409a9f
  .hypothesis/examples/d1328b2e3da390fc/793c6db486c1a037
  .hypothesis/examples/d1328b2e3da390fc/a2f031369663ffd3
  .hypothesis/examples/d1328b2e3da390fc/af8f4cbdb8297048
  .hypothesis/examples/e3879ab8af5e6fa2/425d4c1e3e6921ae
  agir/lib/templates/mail_templates/VOTING_PROXY_REQUEST_EMAIL.html
  agir/lib/templates/mail_templates/VOTING_PROXY_REQUEST_EMAIL.txt
  agir/voting_proxies/components/VotingProxyRequest/NewVotingProxyRequest/NewVotingProxyRequestSuccess.js
  agir/voting_proxies/components/VotingProxyRequest/VotingProxyRequestDetails/VotingProxyRequestDetails.js
  agir/voting_proxies/tasks.py
Labels: feature, bug-staging

#1993 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1995 Page search : update events default results
  agir/front/api_views.py
Labels: minor bug

#1998 Fix search page : fill with past events
  agir/front/api_views.py
Labels: minor bug

#1999 Fix out-of-range error in get_promo_codes function
  agir/groups/actions/promo_codes.py
Labels: Quickfix

#2001 Try to remove duplicate push modal display
  .eslintrc.json
  agir/front/components/allPages/PushModal/PushModal.js
  agir/front/components/legacyPages/renderLegacyPageComponents.js
Labels: minor bug

#2005 Remove mobile app modal
  agir/front/components/allPages/PushModal/MobileAppModal.js
  agir/front/components/allPages/PushModal/MobileAppModal.stories.js
  agir/front/components/allPages/PushModal/PushModal.js
Labels: bug-staging

#2009 Fusion http_task and post_save_task for geocode_person retries
  .hypothesis/examples/020872f66051c7bb/18cf61951bf2d3c3
  .hypothesis/examples/020872f66051c7bb/3098b1d0fefe0f9e
  .hypothesis/examples/020872f66051c7bb/468b8b0df4bee612
  .hypothesis/examples/020872f66051c7bb/e384208426702220
  .hypothesis/examples/95dc7b7ff0e493cd/7b6864a11271ef0d
  .hypothesis/examples/95dc7b7ff0e493cd/b43dea3e13a0687f
  .hypothesis/examples/e3879ab8af5e6fa2/7aa0900108cf5918
  agir/lib/celery.py
  agir/lib/tasks.py
Labels: minor bug

#2010 Fix sentry 2642
  agir/msgs/components/common/hooks.js
Labels: minor bug
