Repository lafranceinsoumise/actionpopulaire.fr, pull requests merged in 2022-01, with the labels that each got.

#1492 Voting proxy request creation
  .hypothesis/examples/05ae5a533c0b69a4/fea8bbc53647810f
  .hypothesis/examples/5b721dd590d22e25/bcfbbc2ffc9f1f41
  .hypothesis/examples/5b721dd590d22e25/c79d0245f4c640ba
  .hypothesis/examples/6e8be5e69c554c1f/a042276cc38836a8
  .hypothesis/examples/6f17816d3eb35872/6f0c61e3ae65df75
  .hypothesis/examples/8c5cf6277a8ac235/126ed08a4386ec78
  .hypothesis/examples/8c5cf6277a8ac235/19c1159276dd1c0b
  .hypothesis/examples/8c5cf6277a8ac235/2ff51b62f224ca2a
  .hypothesis/examples/8c5cf6277a8ac235/71992f5eb4109105
  .hypothesis/examples/b48bda71ee0ad32b/25b79868cd8d7bc1
  .hypothesis/examples/b48bda71ee0ad32b/8239936a6bf78cc3
  .hypothesis/examples/b9d64d99186294e7/64a651a6dc71971d
  .hypothesis/examples/f39eb4bec40384d6/a17c68884ffb40be
  .hypothesis/examples/f39eb4bec40384d6/edab07348983273b
  agir/api/front_urls.py
  agir/api/settings.py
  agir/lib/admin.py
  agir/people/actions/management.py
  agir/voting_proxies/__init__.py
  agir/voting_proxies/actions.py
  agir/voting_proxies/admin.py
  agir/voting_proxies/apps.py
  agir/voting_proxies/migrations/0001_initial.py
  agir/voting_proxies/migrations/__init__.py
  agir/voting_proxies/models.py
  agir/voting_proxies/serializers.py
  agir/voting_proxies/tasks.py
  agir/voting_proxies/tests/__init__.py
  agir/voting_proxies/tests/test_views.py
  agir/voting_proxies/urls.py
  agir/voting_proxies/views.py
Labels: feature

#1512 Update npm dependencies
  agir/front/components/app/ActionButtons/ActionButtons.js
  agir/front/components/app/ActionButtons/ActionButtons.stories.js
  package-lock.json
  package.json
Labels: javascript, dependencies

#1503 Voting proxy retrieve / update
  .hypothesis/examples/05ae5a533c0b69a4/b00b7cd474d4a584
  .hypothesis/examples/6e8be5e69c554c1f/374202b3deafd10b
  .hypothesis/examples/6e8be5e69c554c1f/519e3eb212437b51
  .hypothesis/examples/b48bda71ee0ad32b/bcc66c8d66440a12
  .hypothesis/examples/b48bda71ee0ad32b/fd60c9fc47628f05
  agir/lib/sms.py
  agir/voting_proxies/actions.py
  agir/voting_proxies/serializers.py
  agir/voting_proxies/tests/test_views.py
  agir/voting_proxies/urls.py
  agir/voting_proxies/views.py
Labels: feature

#1517 Hide event page visio link block overflow
  agir/events/components/eventPage/EventPage.js
  agir/events/components/eventPage/OnlineUrlCard.js
Labels: bug-staging

#1498 Delay unread activity and message count API calls
  agir/activity/components/common/hooks.js
  agir/msgs/components/common/hooks.js
Labels: performance

#1519 Re-hide event page visio link block overflow
  agir/events/components/eventPage/EventPage.js
  agir/events/components/eventPage/OnlineUrlCard.js
Labels: bug-staging

#1508 MapPage: add tabs to switch events/groups
  agir/carte/components/common/MapPage.js
Labels: feature

#1513 Messages: update thread menu Card styles
  agir/msgs/components/MessagePage/MessageThreadCard.js
  agir/msgs/components/MessagePage/styledComponents.js
Labels: webdesign

#1521 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1525 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1444 Messages: mute notification on selected message
  agir/front/components/app/Navigation/TopBar/MobileNavBar/RightLink.js
  agir/groups/actions/notifications.py
  agir/groups/components/api.js
  agir/groups/tasks.py
  agir/groups/urls.py
  agir/groups/views/api_views.py
  agir/msgs/components/MessagePage/MessageThreadList.js
  agir/msgs/migrations/0007_supportgroupmessage_mutedlist.py
  agir/msgs/models.py
  agir/msgs/tests.py
  agir/people/actions/management.py
Labels: feature

#1462 Messages: hide messages and comments from inactive people
  agir/front/views.py
  agir/groups/tests/test_messages_api.py
  agir/groups/views/api_views.py
  agir/msgs/actions.py
  agir/msgs/models.py
  agir/msgs/serializers.py
  agir/msgs/tests.py
  agir/msgs/views.py
Labels: feature

#1526 Message : panel participants
  agir/front/components/app/Navigation/TopBar/MobileNavBar/RightLink.js
  agir/front/components/app/Navigation/TopBar/MobileNavBar/SecondaryPageBar.js
  agir/front/components/genericComponents/MessageCard.js
  agir/front/components/genericComponents/MessageDetails.js
  agir/front/components/genericComponents/Modal.js
  agir/groups/components/api.js
  agir/groups/components/groupPage/GroupSettings/GroupMembersPage/MainPanel.js
  agir/groups/urls.py
  agir/groups/views/api_views.py
  agir/msgs/components/MessagePage/ListUsers.js
  agir/msgs/components/MessagePage/MessagePage.js
  agir/msgs/components/MessagePage/MessageThreadList.js
  agir/msgs/components/MessagePage/MessageThreadMenu.js
  agir/msgs/serializers.py
Labels: feature

#1520 Voting proxy request replies
  .hypothesis/examples/05ae5a533c0b69a4/396232def4f2eae2
  .hypothesis/examples/05ae5a533c0b69a4/7097a40b74a9b41e
  .hypothesis/examples/6e8be5e69c554c1f/14ff23bc908d4d77
  .hypothesis/examples/6e8be5e69c554c1f/ea53a4006d479fcc
  .hypothesis/examples/6f17816d3eb35872/091c50b737fb03b2
  .hypothesis/examples/6f17816d3eb35872/5f6c58530f246c2d
  .hypothesis/examples/80fbecba29df1522/011190da04733ce0
  .hypothesis/examples/80fbecba29df1522/724480f1d80e3b37
  .hypothesis/examples/8c5cf6277a8ac235/05b51397553efde4
  .hypothesis/examples/8c5cf6277a8ac235/26ec153b200e3f96
  .hypothesis/examples/8c5cf6277a8ac235/32523a315514b690
  .hypothesis/examples/8c5cf6277a8ac235/59c9ee49293a1296
  .hypothesis/examples/8c5cf6277a8ac235/f4d8040e6c9e6859
  .hypothesis/examples/b48bda71ee0ad32b/108d8add927df330
  .hypothesis/examples/b48bda71ee0ad32b/79dc7c3bf1f7a9e8
  .hypothesis/examples/b48bda71ee0ad32b/846a718525c397dd
  .hypothesis/examples/f39eb4bec40384d6/7756430640476678
  .hypothesis/examples/f39eb4bec40384d6/c23de9af39db9532
  .hypothesis/examples/f39eb4bec40384d6/e3452755879dcbd8
  .hypothesis/examples/f39eb4bec40384d6/f968ebe128763694
  agir/voting_proxies/actions.py
  agir/voting_proxies/admin.py
  agir/voting_proxies/links.py
  agir/voting_proxies/migrations/0001_initial.py
  agir/voting_proxies/models.py
  agir/voting_proxies/serializers.py
  agir/voting_proxies/tasks.py
  agir/voting_proxies/tests/test_actions.py
  agir/voting_proxies/tests/test_tasks.py
  agir/voting_proxies/tests/test_views.py
  agir/voting_proxies/urls.py
  agir/voting_proxies/views.py
Labels: feature

#1530 Messages ; fix mute public email recipients
  agir/groups/tasks.py
Labels: bug-staging

#1538 Update npm dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1545 Messages muted : Feedbacks
  agir/front/components/genericComponents/MessageCard.js
  agir/front/components/genericComponents/MessageDetails.js
  agir/groups/components/groupPage/GroupMessages.js
  agir/groups/components/groupPage/GroupUserActions/EditMembershipDialog.js
  agir/msgs/components/MessagePage/ListUsers.js
  agir/msgs/serializers.py
Labels: feature, bug-staging

#1544 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1537 Voting proxy & Voting proxy request creation pages
  .hypothesis/examples/5b721dd590d22e25/9ba69b19bed76023
  .hypothesis/examples/6e8be5e69c554c1f/1f8765016575ff0d
  .hypothesis/examples/8c5cf6277a8ac235/f1fa66410f084b4f
  .hypothesis/examples/b9d64d99186294e7/3f51c50f9799ea86
  .hypothesis/examples/b9d64d99186294e7/e04525605bc0e3d5
  .hypothesis/examples/f39eb4bec40384d6/a850a83d7b2e1275
  agir/authentication/serializers.py
  agir/donations/components/donationPage/config.js
  agir/front/components/app/routes.config.js
  agir/front/components/formComponents/CheckboxField.js
  agir/front/components/formComponents/SearchAndSelectField.js
  agir/front/components/genericComponents/Steps.js
  agir/front/components/genericComponents/Steps.stories.js
  agir/front/components/genericComponents/themes/2022.js
  agir/front/components/genericComponents/themes/LFI.js
  agir/front/components/genericComponents/themes/images/illustration_2022_BG_D.jpg
  agir/front/components/genericComponents/themes/images/illustration_2022_BG_M.jpg
  agir/front/components/genericComponents/themes/images/illustration_FI_BG_D.jpg
  agir/front/components/genericComponents/themes/images/illustration_FI_BG_M.jpg
  agir/front/urls.py
  agir/voting_proxies/actions.py
  agir/voting_proxies/components/Common/FormSuccess.js
  agir/voting_proxies/components/Common/StyledComponents.js
  agir/voting_proxies/components/Common/StyledPageContainer.js
  agir/voting_proxies/components/Common/VotingDateFields.js
  agir/voting_proxies/components/Common/VotingLocationField.js
  agir/voting_proxies/components/Common/api.js
  agir/voting_proxies/components/VotingProxy/NewVotingProxy/NewVotingProxy.js
  agir/voting_proxies/components/VotingProxy/NewVotingProxy/NewVotingProxyHowTo.js
  agir/voting_proxies/components/VotingProxy/NewVotingProxy/NewVotingProxySuccess.js
  agir/voting_proxies/components/VotingProxy/NewVotingProxy/VotingProxyForm.js
  agir/voting_proxies/components/VotingProxy/NewVotingProxy/form.config.js
  agir/voting_proxies/components/VotingProxy/NewVotingProxy/index.js
  agir/voting_proxies/components/VotingProxyRequest/NewVotingProxyRequest/NewVotingProxyRequest.js
  agir/voting_proxies/components/VotingProxyRequest/NewVotingProxyRequest/NewVotingProxyRequestHowTo.js
  agir/voting_proxies/components/VotingProxyRequest/NewVotingProxyRequest/NewVotingProxyRequestIntro.js
  agir/voting_proxies/components/VotingProxyRequest/NewVotingProxyRequest/NewVotingProxyRequestSuccess.js
  agir/voting_proxies/components/VotingProxyRequest/NewVotingProxyRequest/VotingProxyRequestForm.js
  agir/voting_proxies/components/VotingProxyRequest/NewVotingProxyRequest/form.config.js
  agir/voting_proxies/components/VotingProxyRequest/NewVotingProxyRequest/index.js
  agir/voting_proxies/migrations/0001_initial.py
  agir/voting_proxies/models.py
  agir/voting_proxies/views.py
Labels: feature

#1546 Messages : fix author not shown if not in memberships
  agir/msgs/serializers.py
Labels: bug-staging

#1556 Fix : replace useRouteMatch by vanillaJs in mobile navbar
  agir/front/components/app/Navigation/TopBar/MobileNavBar/RightLink.js
Labels: bug

#1554 Do not use person image as person form page og image
  .hypothesis/examples/05ae5a533c0b69a4/348bde6426688aac
  .hypothesis/examples/7416a4d6aaca03fd/1034d0884793f041
  .hypothesis/examples/7416a4d6aaca03fd/7573d8bbd778f116
  .hypothesis/examples/7416a4d6aaca03fd/783b3a1b55fa0638
  .hypothesis/examples/7416a4d6aaca03fd/7bcf43efa0f5d962
  .hypothesis/examples/7416a4d6aaca03fd/9d2dfdae3241c045
  .hypothesis/examples/7416a4d6aaca03fd/ab7a0c0f61f07c51
  .hypothesis/examples/7416a4d6aaca03fd/ac832972b7a38aff
  .hypothesis/examples/7416a4d6aaca03fd/d0589be754108082
  .hypothesis/examples/7416a4d6aaca03fd/deeb4fc5ed17f2a8
  .hypothesis/examples/7416a4d6aaca03fd/ead0705a9f1a304b
  .hypothesis/examples/df274aa83beb1e49/474790856a4952be
  .hypothesis/examples/df274aa83beb1e49/a513bdbce10f7295
  .hypothesis/examples/df274aa83beb1e49/b1e043aa06e09e9b
  agir/people/views/form.py
Labels: minor bug

#1558 Fix: minor bug message page
  agir/front/components/app/Navigation/TopBar/MobileNavBar/RightLink.js
Labels: bug

#1531 Messages : mark all as read
  agir/front/components/app/Navigation/TopBar/MobileNavBar/RightLink.js
  agir/front/components/genericComponents/ButtonMuteMessage.js
  agir/front/components/genericComponents/MessageCard.js
  agir/front/components/genericComponents/ModalConfirmation.js
  agir/groups/components/api.js
  agir/msgs/components/MessagePage/MessagePage.js
  agir/msgs/components/MessagePage/MessageThreadList.js
  agir/msgs/components/MessagePage/MessageThreadMenu.js
  agir/msgs/urls.py
  agir/msgs/utils.py
  agir/msgs/views.py
  agir/notifications/components/NotificationSettings/NotificationSettingLink.js
Labels: feature

#1563 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1557 Allow re-geocoding on address change if item has not-found type coordinates
  agir/lib/models.py
Labels: minor bug

#1550 Replace Skeleton component Array().keys with for loop
  .hypothesis/examples/80fbecba29df1522/73743179ba5b1b45
  .hypothesis/examples/b9d64d99186294e7/93278921a6c57599
  agir/front/components/genericComponents/Skeleton.js
  agir/front/components/genericComponents/Skeleton.stories.js
Labels: minor bug

#1566 Fix initial size for OpenLayersMap component on group and event detail pages
  agir/events/components/eventPage/EventLocationCard.js
  agir/events/components/eventPage/EventPage.js
  agir/groups/components/groupPage/GroupLocation.js
Labels: minor bug

#1575 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1577 feat: restore event suggestion API view 100km limit for national events
  agir/events/views/api_views.py
Labels: Quickfix

#1578 Preload event static map image in bulk
  .hypothesis/examples/05ae5a533c0b69a4/aabf5b3efdc8d4d1
  .hypothesis/examples/5b721dd590d22e25/3570f82aeaef16d0
  .hypothesis/examples/6f17816d3eb35872/500aefa536632455
  .hypothesis/examples/7416a4d6aaca03fd/12b983e87918d9d5
  .hypothesis/examples/7416a4d6aaca03fd/234a304e7c707ae5
  .hypothesis/examples/7416a4d6aaca03fd/500aefa536632455
  .hypothesis/examples/7416a4d6aaca03fd/50784095e6e87689
  .hypothesis/examples/7416a4d6aaca03fd/5fc2317fa369aaaf
  .hypothesis/examples/7416a4d6aaca03fd/65bb9826ca94b77d
  .hypothesis/examples/7416a4d6aaca03fd/c53d76ab1b28550e
  .hypothesis/examples/7416a4d6aaca03fd/cd6f9c32ca4516fb
  .hypothesis/examples/7416a4d6aaca03fd/d0035f2e3eaa6fbc
  .hypothesis/examples/7416a4d6aaca03fd/d68e191198f14ca0
  .hypothesis/examples/b48bda71ee0ad32b/2f6a7ca78e92f8fe
  .hypothesis/examples/df274aa83beb1e49/1181eba3fae13f88
  agir/events/models.py
  agir/events/serializers.py
  agir/lib/serializers.py
Labels: performance

#1582 chore: update NPM dependencies
  .eslintrc.json
  package-lock.json
  package.json
Labels: javascript, dependencies

#1583 fix: preloaded static map image path retrieval
  .hypothesis/examples/05ae5a533c0b69a4/8d88f2b9c104b528
  .hypothesis/examples/05ae5a533c0b69a4/bc378c2df8d3911d
  .hypothesis/examples/6e8be5e69c554c1f/7d713604d3666294
  .hypothesis/examples/6f17816d3eb35872/74071ec82c1da01e
  .hypothesis/examples/7416a4d6aaca03fd/0249c525944ed96b
  .hypothesis/examples/7416a4d6aaca03fd/093092f01d0b95ac
  .hypothesis/examples/7416a4d6aaca03fd/10baf6c9c9d1e31c
  .hypothesis/examples/7416a4d6aaca03fd/178d62ccf2458135
  .hypothesis/examples/7416a4d6aaca03fd/1cd8ea3aaed294a2
  .hypothesis/examples/7416a4d6aaca03fd/1d820ab442a68ede
  .hypothesis/examples/7416a4d6aaca03fd/2aff291bf6bf21f2
  .hypothesis/examples/7416a4d6aaca03fd/37d65f92d123d076
  .hypothesis/examples/7416a4d6aaca03fd/4a6ef2b43f31bdc4
  .hypothesis/examples/7416a4d6aaca03fd/56b8967972d2ff78
  .hypothesis/examples/7416a4d6aaca03fd/60b5c0692c75860a
  .hypothesis/examples/7416a4d6aaca03fd/8961b12bcc41439b
  .hypothesis/examples/7416a4d6aaca03fd/98c85027d5c29d04
  .hypothesis/examples/7416a4d6aaca03fd/af8267bc93cb3b3c
  .hypothesis/examples/7416a4d6aaca03fd/c02d5daa3243619d
  .hypothesis/examples/7416a4d6aaca03fd/c18bc4b62d4ed215
  .hypothesis/examples/7416a4d6aaca03fd/cc277d8be3304d2a
  .hypothesis/examples/7416a4d6aaca03fd/d64fec7c96d5323e
  .hypothesis/examples/8c5cf6277a8ac235/23d7db80f8a2ef3e
  .hypothesis/examples/df274aa83beb1e49/5aef02f37b514ad2
  .hypothesis/examples/f39eb4bec40384d6/9e94d0f56a3b7c2a
  .hypothesis/examples/f39eb4bec40384d6/c8d7e7b0ef4fc121
  agir/lib/serializers.py
Labels: bug-staging

#1585 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1587 Add no result message plugin to remote selectize choice widget
  agir/lib/templates/custom_fields/remote_selectize_choice.html
Labels: minor bug

#1591 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1593 Fix group search API - decode URI search term
  agir/groups/filters.py
Labels: minor bug

#1592 attempt-to-fix: `ACTIONPOPULAIRE-FRONT-1N2`
  .hypothesis/examples/5b721dd590d22e25/a7fa3ed884f350d8
  .hypothesis/examples/6e8be5e69c554c1f/a755ece2e00adee4
  .hypothesis/examples/6f17816d3eb35872/44a2f5605fe7ff3f
  .hypothesis/examples/b48bda71ee0ad32b/8d72a15d3d2ebd58
  .hypothesis/examples/b9d64d99186294e7/dbee2da1ea011530
  .hypothesis/examples/df274aa83beb1e49/c7697e3e595611ae
  agir/carte/components/map/common.js
Labels: minor bug

#1594 Fix voting proxy creation forms
  .hypothesis/examples/05ae5a533c0b69a4/273587683f7f7706
  .hypothesis/examples/6e8be5e69c554c1f/90fc974d8446673d
  .hypothesis/examples/6f17816d3eb35872/5281c7045c77162d
  .hypothesis/examples/6f17816d3eb35872/82441b82f7ddd7c0
  .hypothesis/examples/8c5cf6277a8ac235/54e7b6607b5ab6c9
  .hypothesis/examples/8c5cf6277a8ac235/a5fed34c415b1493
  .hypothesis/examples/8c5cf6277a8ac235/e78acce17765047d
  .hypothesis/examples/b9d64d99186294e7/03d0d95c3df6ac2c
  agir/front/components/formComponents/SearchAndSelectField.js
  agir/voting_proxies/components/Common/VotingLocationField.js
  agir/voting_proxies/components/VotingProxy/NewVotingProxy/VotingProxyForm.js
  agir/voting_proxies/components/VotingProxy/NewVotingProxy/form.config.js
  agir/voting_proxies/components/VotingProxyRequest/NewVotingProxyRequest/VotingProxyRequestForm.js
  agir/voting_proxies/components/VotingProxyRequest/NewVotingProxyRequest/form.config.js
  agir/voting_proxies/migrations/0002_blankable_polling_station_number_field.py
  agir/voting_proxies/models.py
  agir/voting_proxies/serializers.py
  agir/voting_proxies/tasks.py
  agir/voting_proxies/tests/test_views.py
Labels: feature, bug-staging

#1595 Messages list : load messages on scroll
  agir/activity/components/ActivityPage/ActivityList.js
  agir/activity/components/common/hooks.js
  agir/msgs/components/MessagePage/MessagePage.js
  agir/msgs/components/MessagePage/MessageThreadList.js
  agir/msgs/components/MessagePage/MessageThreadMenu.js
  agir/msgs/components/common/hooks.js
  agir/msgs/tests.py
  agir/msgs/views.py
Labels: feature, performance

#1600 Fix: add title of mobile navbar
  agir/front/components/app/Navigation/TopBar/MobileNavBar/SecondaryPageBar.js
Labels: bug

#1601 Throttle voting proxy creation api endpoint requests
  .hypothesis/examples/05ae5a533c0b69a4/8ae2c75a059c6c5d
  .hypothesis/examples/05ae5a533c0b69a4/db186856e85a0343
  .hypothesis/examples/b48bda71ee0ad32b/a0994bc402e075d8
  .hypothesis/examples/b9d64d99186294e7/1e08865c1056d4eb
  .hypothesis/examples/f39eb4bec40384d6/c35373ca4df1b178
  agir/voting_proxies/components/Common/api.js
  agir/voting_proxies/components/VotingProxy/NewVotingProxy/NewVotingProxyHowTo.js
  agir/voting_proxies/components/VotingProxy/NewVotingProxy/VotingProxyForm.js
  agir/voting_proxies/components/VotingProxyRequest/NewVotingProxyRequest/NewVotingProxyRequestHowTo.js
  agir/voting_proxies/components/VotingProxyRequest/NewVotingProxyRequest/VotingProxyRequestForm.js
  agir/voting_proxies/tests/test_views.py
  agir/voting_proxies/views.py
Labels: feature, bug-staging

#1602 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1603 Fix voting proxy sms sender
  .hypothesis/examples/05ae5a533c0b69a4/353d5b45efb8cfe7
  .hypothesis/examples/05ae5a533c0b69a4/e252f2dbfae8cc7d
  .hypothesis/examples/6e8be5e69c554c1f/84bf673052cc2202
  .hypothesis/examples/b48bda71ee0ad32b/796c41ed58594df3
  agir/voting_proxies/components/VotingProxy/NewVotingProxy/VotingProxyForm.js
  agir/voting_proxies/tasks.py
Labels: feature

#1605 Add custom opengraph properties to voting proxy and vp request views
  agir/front/static/front/assets/og_image_vp.jpg
  agir/front/static/front/assets/og_image_vpr.jpg
  agir/front/urls.py
  agir/front/views.py
Labels: feature

#1615 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1606 Search page : feedbacks
  agir/carte/components/page__eventMap/EventMap.js
  agir/carte/components/page__groupMap/GroupMap.js
  agir/front/api_views.py
  agir/front/components/SearchPage/SearchEventPage.js
  agir/front/components/SearchPage/SearchGroupPage.js
  agir/front/components/SearchPage/SearchPage.js
  agir/front/components/SearchPage/api.js
  agir/front/components/SearchPage/config.js
  agir/front/components/SearchPage/resultsComponents.js
  agir/front/components/SearchPage/searchComponents.js
  agir/front/components/SearchPage/styledComponents.js
  agir/front/components/SearchPage/useSearch.js
  agir/front/components/app/routes.config.js
  agir/front/components/genericComponents/Tabs.js
  agir/front/urls.py
  agir/groups/components/groupPage/GroupSuggestions.js
Labels: performance

#1623 Fix SearchPages : missing import
  agir/front/components/SearchPage/SearchPage.js
  agir/front/components/SearchPage/useSearch.js
Labels: bug-staging

#1635 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1618 Static map image - replace distance with dwithin query
  .hypothesis/examples/5b721dd590d22e25/6717ade6c72e3674
  .hypothesis/examples/6e8be5e69c554c1f/72981036eb963eeb
  .hypothesis/examples/b9d64d99186294e7/51b0a3a33f059e11
  agir/carte/models.py
  agir/events/models.py
  agir/events/views/event_views.py
  agir/groups/views/public_views.py
  agir/lib/serializers.py
  agir/lib/tasks.py
Labels: do not merge, wait next release, performance

#1626 Reduce SupportGroupMessageParticipantSerializer query time
  .hypothesis/examples/05ae5a533c0b69a4/034bcdc3f5162aad
  .hypothesis/examples/05ae5a533c0b69a4/1e3d473d9f934b2d
  .hypothesis/examples/6e8be5e69c554c1f/d41432815ebc014b
  .hypothesis/examples/6f17816d3eb35872/6215aa533ecf1dba
  .hypothesis/examples/6f17816d3eb35872/e1517a1ace5c7c7e
  .hypothesis/examples/8c5cf6277a8ac235/46700d9c8caf09f5
  agir/groups/views/api_views.py
  agir/msgs/serializers.py
Labels: performance

#1617 Try to reduce api/session query time
  .hypothesis/examples/6e8be5e69c554c1f/ca706dfbc157c57d
  .hypothesis/examples/8c5cf6277a8ac235/9c9599672d515e92
  .hypothesis/examples/b48bda71ee0ad32b/96459bd8453bcff5
  agir/authentication/serializers.py
  agir/authentication/views/api_views.py
  agir/front/components/app/ActionButtons/ActionButtons.stories.js
  agir/front/components/app/ActionButtons/actions.config.js
  agir/front/components/app/Navigation/SideBar/index.js
  agir/front/components/app/Navigation/navigation.config.json
  agir/front/components/formComponents/MessageModal/MessageStep.js
  agir/front/components/mockData/routes.json
  agir/front/components/offline/hooks.js
Labels: performance

#1616 Try to improve homepage api call performances
  .hypothesis/examples/6e8be5e69c554c1f/f51ff51ff7649973
  .hypothesis/examples/b9d64d99186294e7/1174280997fbb567
  .hypothesis/examples/b9d64d99186294e7/a2844d9eb67ef179
  .hypothesis/examples/df274aa83beb1e49/497194d0a8f57e64
  agir/activity/actions.py
  agir/activity/components/ActivityPage/ActivityList.js
  agir/activity/components/ActivityPage/ActivityMergerAnnouncement.js
  agir/activity/components/common/hooks.js
  agir/front/components/serviceWorker/cachedRoutes.config.js
  agir/mailing/models.py
Labels: do not merge, wait next release, performance
