Repository lafranceinsoumise/actionpopulaire.fr, pull requests merged in 2022-02, with the labels that each got.

#1610 Add grand event suggestions to homepage
  .hypothesis/examples/05ae5a533c0b69a4/094ba79d05933d56
  .hypothesis/examples/6f17816d3eb35872/e42c13d2f10749ba
  .hypothesis/examples/f39eb4bec40384d6/6599e47a365c1c4f
  agir/events/components/agendaPage/Agenda.js
  agir/events/components/agendaPage/EventSuggestions.js
  agir/events/components/agendaPage/api.js
  agir/events/models.py
  agir/events/serializers.py
  agir/events/urls.py
  agir/events/views/api_views.py
  agir/front/components/serviceWorker/cachedRoutes.config.js
  agir/front/views.py
Labels: performance

#1640 fix: ACTIONPOPULAIRE-FRONT-1TG
  agir/msgs/components/common/hooks.js
Labels: minor bug

#1609 Fix admin people person changelist AnimateMoreThanOneGroup filter
  agir/people/admin/panels.py
Labels: minor bug

#1648 Fix map icon background color
  agir/carte/components/map/common.js
Labels: bug

#1647 Event suggestion API - replace distance with dwithin query
  agir/events/views/api_views.py
Labels: performance

#1650 Search fix : zindex isolation for groups on mobile
  agir/groups/components/groupPage/GroupSuggestions.js
Labels: bug

#1653 Fix map icon background color
  agir/carte/components/map/common.js
Labels: bug-staging

#1651 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1654 Reduce group event API views query time
  .hypothesis/examples/b48bda71ee0ad32b/3d1ad5a6f6a9e92c
  agir/groups/views/api_views.py
Labels: performance

#1638 Lazy-load activity card embedded event cards
  .hypothesis/examples/05ae5a533c0b69a4/6e5e9712912cb546
  agir/activity/actions.py
  agir/activity/components/ActivityPage/ActivityCard/ActivityCard.stories.js
  agir/activity/components/ActivityPage/ActivityCard/GenericCard.js
  agir/activity/components/ActivityPage/ActivityCard/GenericCardContainer.js
  agir/activity/components/ActivityPage/ActivityCard/GroupMembershipLimitReminderCard.js
  agir/activity/components/ActivityPage/ActivityCard/index.js
  agir/activity/components/common/activity.config.js
  agir/activity/serializers.py
  agir/events/components/common/api.js
  agir/events/serializers.py
  agir/events/tests/test_views.py
  agir/events/urls.py
  agir/events/views/api_views.py
  agir/front/components/serviceWorker/cachedRoutes.config.js
  agir/front/views.py
Labels: performance

#1652 Add event rsvp link to event admin page
  agir/events/admin/panels.py
Labels: bug-staging

#1662 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1656 Do not filter view context list map subtype configs
  .hypothesis/examples/5b721dd590d22e25/9330a2ab195fd671
  .hypothesis/examples/6f17816d3eb35872/70e31d747578ca54
  agir/carte/views.py
Labels: minor bug

#1628 chore: replace 'react-use-gesture' with '@use-gesture/react'
  agir/front/components/app/IntroApp.js
  agir/front/components/genericComponents/InputRange.js
  agir/front/components/genericComponents/Tabs.js
  agir/front/components/genericComponents/Tabs.stories.js
  package-lock.json
  package.json
Labels: javascript, dependencies

#1663 Limit message page API endpoints' revalidations
  agir/front/components/allPages/SWRContext.js
  agir/front/components/genericComponents/ButtonMuteMessage.js
  agir/front/components/genericComponents/MessageDetails.js
  agir/front/views.py
  agir/msgs/components/common/hooks.js
Labels: performance

#1664 Raise exception if shorten_url request fails
  .hypothesis/examples/8c5cf6277a8ac235/75a582a4b13ee033
  .hypothesis/examples/b48bda71ee0ad32b/502614135e8095ec
  .hypothesis/examples/f39eb4bec40384d6/82b4a2350afa1761
  agir/api/settings.py
  agir/lib/utils.py
  agir/voting_proxies/tests/test_tasks.py
Labels: bug

#1586 Voting proxy matching confirmation page
  .hypothesis/examples/05ae5a533c0b69a4/9dd7f5ac1632b799
  .hypothesis/examples/05ae5a533c0b69a4/ad6e034d20cca0ed
  .hypothesis/examples/05ae5a533c0b69a4/ae467d60cc33b407
  .hypothesis/examples/05ae5a533c0b69a4/b8e287f93558d4f6
  .hypothesis/examples/05ae5a533c0b69a4/f27c7f0cd65d1abf
  .hypothesis/examples/5b721dd590d22e25/843fb1b3ec89fd74
  .hypothesis/examples/5b721dd590d22e25/eeb5125b59d69e68
  .hypothesis/examples/6e8be5e69c554c1f/0aac06df3f2b92e5
  .hypothesis/examples/6e8be5e69c554c1f/506cf4329f0ed76c
  .hypothesis/examples/6e8be5e69c554c1f/a0e7fafa227a8fdb
  .hypothesis/examples/6e8be5e69c554c1f/cac6814f8dce92f1
  .hypothesis/examples/6f17816d3eb35872/433c6548899f3073
  .hypothesis/examples/8c5cf6277a8ac235/39598d835ac2453e
  .hypothesis/examples/b48bda71ee0ad32b/33bc81e3527710d2
  .hypothesis/examples/b48bda71ee0ad32b/76df60148eee0370
  .hypothesis/examples/b48bda71ee0ad32b/77653c3078e2cb7f
  .hypothesis/examples/b9d64d99186294e7/e8faaa65c1158c8c
  .hypothesis/examples/f39eb4bec40384d6/cb02ea4dd6a175d6
  .hypothesis/examples/f39eb4bec40384d6/dfad4b2fc224cf36
  .hypothesis/examples/f39eb4bec40384d6/fc39d1640ef40ab4
  agir/front/components/app/routes.config.js
  agir/front/urls.py
  agir/voting_proxies/actions.py
  agir/voting_proxies/components/Common/api.js
  agir/voting_proxies/components/VotingProxy/ReplyToVotingProxyRequests/NoRequestFound.js
  agir/voting_proxies/components/VotingProxy/ReplyToVotingProxyRequests/ReplySuccess.js
  agir/voting_proxies/components/VotingProxy/ReplyToVotingProxyRequests/ReplyToVotingProxyRequests.js
  agir/voting_proxies/components/VotingProxy/ReplyToVotingProxyRequests/ReplyingForm.js
  agir/voting_proxies/components/VotingProxy/ReplyToVotingProxyRequests/index.js
  agir/voting_proxies/components/VotingProxyRequest/VotingProxyRequestDetails/VotingProxyRequestDetails.js
  agir/voting_proxies/components/VotingProxyRequest/VotingProxyRequestDetails/VotingProxyWidget.js
  agir/voting_proxies/components/VotingProxyRequest/VotingProxyRequestDetails/index.js
  agir/voting_proxies/links.py
  agir/voting_proxies/serializers.py
  agir/voting_proxies/tasks.py
  agir/voting_proxies/tests/test_views.py
  agir/voting_proxies/urls.py
  agir/voting_proxies/views.py
Labels: feature

#1668 Messages list : hide unread on select message, bind new mutation to message actions
  agir/msgs/components/MessagePage/MessagePage.js
  agir/msgs/components/MessagePage/MessageThreadCard.js
  agir/msgs/components/common/hooks.js
Labels: bug, feature

#1675 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1622 Replace `isAuthenticated` permission class with `isPersonPermission`
  .hypothesis/examples/05ae5a533c0b69a4/cc5185ba39a7f5c1
  .hypothesis/examples/5b721dd590d22e25/314ab5013a91351c
  agir/activity/views.py
  agir/events/views/api_views.py
  agir/groups/views/api_views.py
  agir/msgs/views.py
Labels: minor bug

#1665 Message participants: fix active people and total participants
  agir/front/components/genericComponents/MessageDetails.js
  agir/msgs/components/MessagePage/ListUsers.js
  agir/msgs/serializers.py
Labels: bug

#1655 Messages list : to show loader using counter
  agir/msgs/components/MessagePage/ListUsers.js
  agir/msgs/components/MessagePage/MessagePage.js
  agir/msgs/components/MessagePage/MessageThreadList.js
  agir/msgs/components/MessagePage/MessageThreadMenu.js
  agir/msgs/components/common/hooks.js
Labels: minor bug

#1657 Search page : improve UI & refactor
  agir/front/components/SearchPage/SearchEventPage.js
  agir/front/components/SearchPage/SearchGroupPage.js
  agir/front/components/SearchPage/SearchPage.js
  agir/front/components/SearchPage/searchComponents.js
  agir/front/components/SearchPage/useFilters.js
Labels: webdesign, performance

#1676 Add explicit errors for new message modal
  agir/front/components/formComponents/MessageModal/MessageStep.js
  agir/front/components/formComponents/MessageModal/Modal.js
Labels: webdesign

#1677 Fix ACTIONPOPULAIRE-FRONT-1X7 : missing group card fund link
  agir/groups/components/groupComponents/GroupCard.js
Labels: minor bug

#1679 Fix message page circular hook dependency `ACTIONPOPULAIRE-FRONT-1XH`
  agir/msgs/components/MessagePage/MessagePage.js
  agir/msgs/components/common/hooks.js
Labels: minor bug

#1684 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1680 Try to reduce EventRsvpedAPIView query time
  .hypothesis/examples/6e8be5e69c554c1f/447ef404b6f38727
  agir/events/views/api_views.py
Labels: performance

#1681 Fix missing link from funding group card button
  agir/groups/components/groupComponents/GroupCard.js
Labels: bug-staging

#1686 Try to reduce search API query time
  agir/events/models.py
  agir/events/serializers.py
  agir/front/api_views.py
  agir/front/components/genericComponents/EventCard.js
  agir/groups/models.py
  agir/groups/serializers.py
Labels: performance, bug-staging

#1685 Remove legacy react-spring import
  agir/events/components/common/UpcomingEvents/UpcomingEvents.js
Labels: performance

#1687 Fix group search result alignment
  agir/front/components/SearchPage/resultsComponents.js
Labels: minor bug

#1688 Fix group page JoinGroupDialog and MessageModal control conflict
  agir/front/components/genericComponents/MessageCard.js
  agir/groups/components/groupPage/GroupUserActions/JoinGroupDialog.js
  agir/groups/components/groupPage/GroupUserActions/index.js
Labels: bug

#1691 Avoid duplicate search page results
  agir/front/api_views.py
  agir/groups/components/groupPage/GroupSuggestionCard.js
Labels: bug-staging

#1702 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1706 fix: `ACTIONPOPULAIRE-FRONT-1YN` => missing message hook deps
  agir/front/components/app/Navigation/TopBar/DesktopNavBar/RightLinks.js
  agir/front/components/genericComponents/MessageCard.js
  agir/msgs/components/MessagePage/ListUsers.js
  agir/msgs/components/common/hooks.js
Labels: minor bug

#1693 Try to reduce segmented event suggestion query time
  agir/events/models.py
  agir/events/views/api_views.py
Labels: performance

#1695 Try to reduce the number of queries to retrieve announcements by segment
  .hypothesis/examples/f39eb4bec40384d6/01163dbd490f2c53
  agir/activity/actions.py
Labels: performance

#1707 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1708 Remove `react-icons` NPM dependency
  agir/events/components/EventSettings/EventMember.js
  agir/front/components/formComponents/MessageModal/EventStep.js
  agir/front/components/formComponents/MessageModal/GroupStep.js
  agir/front/components/genericComponents/FaIcon.js
  agir/front/components/genericComponents/LinkIcon.js
  agir/front/components/genericComponents/MessageCard.js
  agir/front/components/genericComponents/ShareContentUrl.js
  package-lock.json
  package.json
Labels: performance

#1713 Avoid useless EventSerializer queries if only card fields are used
  .hypothesis/examples/05ae5a533c0b69a4/7905ca5c0f152498
  .hypothesis/examples/b48bda71ee0ad32b/edd2817f209d074f
  agir/events/models.py
  agir/events/serializers.py
Labels: performance

#1715 Avoid useSelectMessage hook error on missing mutateMessages function
  agir/msgs/components/common/hooks.js
Labels: minor bug

#1717 Fix link create group
  agir/front/components/genericComponents/Onboarding.js
Labels: bug

#1719 Show footer on search pages
  agir/front/components/app/routes.config.js
Labels: webdesign

#1720 Hide result count in general search page result tab
  agir/front/components/SearchPage/SearchEventPage.js
  agir/front/components/SearchPage/SearchGroupPage.js
  agir/front/components/SearchPage/SearchPageTab.js
  agir/front/components/SearchPage/resultsComponents.js
Labels: bug-staging

#1721 Styles: show hidden text on links with same color than their background
  agir/lib/static/admin/prod_colors.css
  agir/lib/static/admin/staging_colors.css
Labels: webdesign

#1722 Update profile newsletters fix
  agir/notifications/components/NotificationSettings/NotificationSettings.js
  agir/notifications/components/common/notifications.config.js
Labels: bug-staging

#1726 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1716 Optimize SupportGroupSerializer queries
  .hypothesis/examples/5b721dd590d22e25/b34946a2cbfb86a7
  .hypothesis/examples/6f17816d3eb35872/93fd3d62a9042036
  agir/events/serializers.py
  agir/front/api_views.py
  agir/groups/models.py
  agir/groups/serializers.py
  agir/groups/views/api_views.py
Labels: performance

#1723 Separate several messages cards with spacer
  agir/front/components/genericComponents/MessageCard.js
  agir/groups/components/groupPage/GroupPage/Routes/RoutePreviews.js
Labels: webdesign

#1696 Try to reduce event page first exec time
  .hypothesis/examples/df274aa83beb1e49/17ac254f23ca3a8f
  agir/events/components/eventPage/DesktopEventPage.js
  agir/events/components/eventPage/EventPage.js
  agir/events/components/eventPage/EventPage.stories.js
  agir/events/components/eventPage/MobileEventPage.js
  agir/events/components/eventPage/OnlineUrlCard.js
  agir/events/components/eventPage/ReportFormCard.js
  agir/front/components/offline/hooks.js
Labels: performance

#1718 Mark all messages as read in only two db queries (instead of two for each message)
  .hypothesis/examples/6f17816d3eb35872/aac516504d1ea885
  agir/msgs/views.py
Labels: performance

#1729 Fix : notification settings
  agir/notifications/components/NotificationSettings/NotificationSettings.js
  agir/notifications/components/common/notifications.config.js
Labels: bug-staging

#1731 Message list : unread mutations
  agir/msgs/components/MessagePage/MessagePage.js
  agir/msgs/components/MessagePage/MessageThreadMenu.js
  agir/msgs/components/common/hooks.js
Labels: minor bug

#1736 Group member list filter/sort fixes
  agir/groups/components/groupPage/GroupSettings/GroupMemberList/GroupMemberList.js
Labels: bug-staging

#1738 fix ACTIONPOPULAIRE-FRONT-1Z4
  agir/groups/components/groupPage/hooks/messages.js
Labels: minor bug

#1740 chore: update python dependencies
  .hypothesis/examples/05ae5a533c0b69a4/5b8fe3169d2defce
  .hypothesis/examples/8c5cf6277a8ac235/891bf62d53aa86d0
  .hypothesis/examples/b9d64d99186294e7/cc1e5f94409d2dd3
  poetry.lock
  pyproject.toml
Labels: python, dependencies

#1747 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1735 Try to reduce message participant API query time
  .hypothesis/examples/05ae5a533c0b69a4/194e1865015f34e4
  .hypothesis/examples/05ae5a533c0b69a4/e14abd14c789a30f
  .hypothesis/examples/5b721dd590d22e25/4d88428cd42295b4
  .hypothesis/examples/6f17816d3eb35872/80bcf6b7f00cd429
  .hypothesis/examples/6f17816d3eb35872/ddce5021f492a27d
  .hypothesis/examples/8c5cf6277a8ac235/39598d835ac2453e
  .hypothesis/examples/b48bda71ee0ad32b/c72169ed145b7523
  .hypothesis/examples/b9d64d99186294e7/9ed316b5af84e1f3
  .hypothesis/examples/b9d64d99186294e7/fbc0a11db985769d
  .hypothesis/examples/f39eb4bec40384d6/66a04f918b0b884a
  agir/groups/rules.py
  agir/groups/views/api_views.py
  agir/msgs/rules.py
  agir/msgs/serializers.py
Labels: performance

#1759 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1766 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1768 Add admin event timezone field
  agir/events/admin/panels.py
Labels: Quickfix

#1750 Update nuntius to v2.3.0b2
  .hypothesis/examples/6e8be5e69c554c1f/5bef8458a5734d8a
  .hypothesis/examples/6e8be5e69c554c1f/dc1d156871429f83
  .hypothesis/examples/6e8be5e69c554c1f/f8a3421cbf39c769
  .hypothesis/examples/6f17816d3eb35872/6f0d684115196969
  .hypothesis/examples/8c5cf6277a8ac235/3d252bc523bce85f
  .hypothesis/examples/f39eb4bec40384d6/b9cb1b4ad5bdd3c7
  agir/api/settings.py
  agir/mailing/admin.py
  agir/people/actions/management.py
  agir/people/models.py
  poetry.lock
  pyproject.toml
Labels: feature

#1769 Allow html description in email notification bindings
  agir/events/tasks.py
  agir/groups/tasks.py
Labels: bug-staging

#1772 Fix unread message : await query unread to mutate message
  agir/msgs/components/MessagePage/MessagePage.js
Labels: bug-staging

#1776 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1781 Update event email description and image layout
  agir/events/admin/forms.py
  agir/groups/tasks.py
  agir/groups/tests/test_forms.py
  agir/lib/templates/mail_templates/EVENT_SUGGESTION.html
  agir/lib/templates/mail_templates/NEW_EVENT_MY_GROUPS_NOTIFICATION.html
Labels: bug-staging

#1786 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1782 Message : allow locking thread switch permission
  agir/front/components/app/Navigation/TopBar/MobileNavBar/RightLink.js
  agir/front/components/formComponents/CommentField.js
  agir/front/components/genericComponents/ButtonLockMessage.js
  agir/front/components/genericComponents/MessageCard.js
  agir/groups/components/api.js
  agir/groups/tests/test_messages_api.py
  agir/groups/urls.py
  agir/groups/views/api_views.py
  agir/msgs/migrations/0008_supportgroupmessage_is_locked.py
  agir/msgs/migrations/0009_alter_supportgroupmessage_is_locked.py
  agir/msgs/models.py
  agir/msgs/rules.py
  agir/msgs/serializers.py
Labels: feature

#1787 Fix upcoming event reminder notification title
  agir/notifications/serializers/activity_notifications.py
  agir/notifications/tests/test_activity_notification_serializers.py
Labels: minor bug

#1790 Avoid showing too many messages to superusers
  agir/msgs/actions.py
  agir/msgs/components/MessagePage/MessageThreadCard.js
  agir/msgs/components/common/utils.js
  agir/msgs/serializers.py
  agir/msgs/utils.py
  agir/msgs/views.py
Labels: minor bug

#1798 Fix unread badge when unread message
  agir/msgs/components/MessagePage/MessageThreadCard.js
Labels: minor bug

#1789 TokTok card, page and links
  agir/events/components/TokTok/TokTokCard.js
  agir/events/components/TokTok/TokTokCard.stories.js
  agir/events/components/TokTok/TokTokPreview/HowTo.js
  agir/events/components/TokTok/TokTokPreview/HowTo.stories.js
  agir/events/components/TokTok/TokTokPreview/StyledComponents.js
  agir/events/components/TokTok/TokTokPreview/StyledComponents.stories.js
  agir/events/components/TokTok/TokTokPreview/index.js
  agir/events/components/TokTok/images/TokTok.svg
  agir/events/components/TokTok/images/TokTokBG.jpg
  agir/events/components/TokTok/images/TokTokBannerBGLarge.jpg
  agir/events/components/TokTok/images/TokTokBannerBGSmall.jpg
  agir/events/components/TokTok/images/TokTokLogoLarge.jpg
  agir/events/components/common/utils.js
  agir/events/components/createEventPage/CreateEvent.js
  agir/events/components/eventPage/DesktopEventPage.js
  agir/events/components/eventPage/MobileEventPage.js
  agir/events/components/eventPage/ReportFormCard.js
  agir/front/components/ActionToolsPage/ActionTools.js
  agir/front/components/ActionToolsPage/DesktopActionToolsPage.js
  agir/front/components/ActionToolsPage/MobileActionToolsPage.js
  agir/front/components/app/ActionButtons/actions.config.js
  agir/front/components/app/routes.config.js
  agir/front/components/genericComponents/_variables.scss
  agir/front/components/globalContext/nonReactRoutes.config.json
  agir/front/urls.py
Labels: feature

#1805 Use local start/end in event page schema.org data
  agir/front/views.py
Labels: bug-staging

#1810 Skip full group modal after trying to join a full group
  agir/groups/components/groupPage/GroupUserActions/JoinGroupDialog.js
  agir/groups/components/groupPage/GroupUserActions/JoinGroupDialog.stories.js
  agir/groups/components/groupPage/GroupUserActions/index.js
Labels: bug-staging

#1803 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#1814 quickfix: rollback `babel-plugin-styled-components` to v2.0.2
  package-lock.json
  package.json
Labels: Quickfix

#1815 quickfix: comment out broken mobile nav bar right link code
  agir/front/components/app/Navigation/TopBar/MobileNavBar/RightLink.js
Labels: Quickfix

#1816 Restore tablet nav bar group page link
  agir/front/components/app/Navigation/TopBar/TopBar.js
Labels: minor bug

#1804 Split user groups and user group suggestions into two endpoints
  agir/activity/components/ActivityPage/ActivityCard/GenericCardContainer.js
  agir/donations/components/donationPage/DonationPage.js
  agir/front/components/serviceWorker/cachedRoutes.config.js
  agir/front/views.py
  agir/groups/components/groupsPage/GroupsPage.js
  agir/groups/urls.py
  agir/groups/views/api_views.py
  agir/notifications/components/NotificationSettings/NotificationSettings.js
  agir/notifications/components/common/notifications.config.js
  agir/people/components/contacts/CreateContactPage/index.js
Labels: performance

#1806 Limit PastRsvpedEventAPIView results to maximum 20 events
  .hypothesis/examples/5b721dd590d22e25/127505721d00365d
  .hypothesis/examples/a8f3af75ba35d1d2/34e51adafe31669f
  .hypothesis/examples/a8f3af75ba35d1d2/9bfe6542db07637a
  .hypothesis/examples/a8f3af75ba35d1d2/e1e8a7488e53b74a
  .hypothesis/examples/ddb76f4f03fab698/158abe08ccdd2473
  .hypothesis/examples/ddb76f4f03fab698/9ad573a7d3506314
  .hypothesis/examples/ddb76f4f03fab698/a57a4a05e525358f
  .hypothesis/examples/ddb76f4f03fab698/d6f200dc70f92b05
  .hypothesis/examples/df274aa83beb1e49/541bcf4157df1077
  .hypothesis/examples/f3043d07df515730/2ce22c9255256111
  .hypothesis/examples/f3043d07df515730/78cdf039f5224443
  .hypothesis/examples/f3043d07df515730/88218917d79f1051
  .hypothesis/examples/f3043d07df515730/97a78b84784c93aa
  .hypothesis/examples/f3043d07df515730/9a2715d1fe7e80f3
  .hypothesis/examples/f3043d07df515730/db8e074b09834c47
  agir/events/views/api_views.py
Labels: performance

#1807 Preload group subtype in LegacyGroupSearchAPIView queryset
  .hypothesis/examples/a8f3af75ba35d1d2/11bc54156fbd8147
  .hypothesis/examples/dd8c1e5b4eeb95d9/00d6c7a78586f67f
  .hypothesis/examples/dd8c1e5b4eeb95d9/0be1298449a1a990
  .hypothesis/examples/dd8c1e5b4eeb95d9/1ecae50c43de7bee
  .hypothesis/examples/dd8c1e5b4eeb95d9/392b0011f21cbfe5
  .hypothesis/examples/ddb76f4f03fab698/86b3a5f4db172d5b
  .hypothesis/examples/ddb76f4f03fab698/defc964d50ba752c
  .hypothesis/examples/f3043d07df515730/46dd630891064bdf
  .hypothesis/examples/f3043d07df515730/5d97ec69b83c83fc
  .hypothesis/examples/f3043d07df515730/b1da8ec5efcd1b0c
  agir/groups/views/api_views.py
Labels: performance

#1809 Fix full group page onboarding mobile layout
  agir/groups/components/fullGroupPage/FullGroupPage.js
Labels: minor bug

#1818 Fix eslint broken config
  .eslintrc.json
  package-lock.json
  package.json
Labels: minor bug

#1821 Exclude hidden events from send_event_required_document_reminders
  .hypothesis/examples/6e8be5e69c554c1f/d3d05f85cf4daa99
  .hypothesis/examples/6e8be5e69c554c1f/de1bf3fed59a20b8
  .hypothesis/examples/6f17816d3eb35872/375bf6d207b9472b
  .hypothesis/examples/dd8c1e5b4eeb95d9/000523dfe88917f2
  .hypothesis/examples/dd8c1e5b4eeb95d9/6bbab31e404b210d
  .hypothesis/examples/dd8c1e5b4eeb95d9/e36c6772efc51bc8
  .hypothesis/examples/ddb76f4f03fab698/76b514b298dab0e3
  agir/events/management/commands/send_event_required_document_reminders.py
Labels: bug

#1819 chore: update NPM dependencies
  .hypothesis/examples/6f17816d3eb35872/3c5611e878c9baa5
  .hypothesis/examples/ddb76f4f03fab698/35094f86b14a5558
  package-lock.json
  package.json
Labels: javascript, dependencies

#1823 Remove `équipe` from FullGroupWarning
  agir/groups/components/groupPage/GroupSettings/GroupMembersPage/MainPanel.js
Labels: minor bug

#1827 Disable focus-on-click for homepage action buttons
  agir/front/components/app/ActionButtons/ActionButton.js
Labels: minor bug

#1828 Restore full group email and notification
  .hypothesis/examples/6e8be5e69c554c1f/dfc4768d9f9eef64
  agir/groups/actions/notifications.py
  agir/groups/tasks.py
Labels: bug-staging

#1830 Nuntius push campaigns
  .hypothesis/examples/5b721dd590d22e25/814a95ed1d996f56
  .hypothesis/examples/6e8be5e69c554c1f/5bef8458a5734d8a
  .hypothesis/examples/6e8be5e69c554c1f/dc1d156871429f83
  .hypothesis/examples/6e8be5e69c554c1f/f8a3421cbf39c769
  .hypothesis/examples/6f17816d3eb35872/6f0d684115196969
  .hypothesis/examples/8c5cf6277a8ac235/3d252bc523bce85f
  .hypothesis/examples/8c5cf6277a8ac235/9a8fff339a95f035
  .hypothesis/examples/f39eb4bec40384d6/b9cb1b4ad5bdd3c7
  agir/api/settings.py
  agir/mailing/admin.py
  agir/people/actions/management.py
  agir/people/models.py
  poetry.lock
  pyproject.toml
Labels: feature

#1829 Fix missing group membership transfer href on member settings
  agir/groups/components/groupPage/GroupSettings/GroupMembersPage/MainPanel.js
Labels: bug
