Repository lafranceinsoumise/actionpopulaire.fr, pull requests merged in 2022-04, with the labels that each got.

#2013 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#2008 Fix sentry 2761
  agir/front/components/formComponents/CommentField.js
  agir/front/components/genericComponents/MessageCard.js
  agir/lib/components/utils/hooks.js
Labels: minor bug

#2014 Managers : allow to update event settings
  agir/events/components/EventSettings/EventSettings.js
  agir/events/components/eventPage/DesktopEventPage.js
  agir/events/components/eventPage/EventHeader.js
  agir/events/components/eventPage/MobileEventPage.js
  agir/events/rules.py
  agir/events/serializers.py
  agir/events/tests/test_rules.py
Labels: bug-staging

#2019 Fusion chained exclusive celery task decorators
  .hypothesis/examples/6a2e6cafece44878/a8bdc5b285ea18e7
  .hypothesis/examples/a8f3af75ba35d1d2/f18c275fe3529a3c
  .hypothesis/examples/df274aa83beb1e49/f6432d909f045e72
  agir/api/celery.py
  agir/authentication/tasks.py
  agir/checks/tasks.py
  agir/donations/tasks.py
  agir/events/tasks.py
  agir/groups/tasks.py
  agir/lib/celery.py
  agir/lib/tasks.py
  agir/loans/tasks.py
  agir/msgs/tasks.py
  agir/municipales/tasks.py
  agir/notifications/tasks.py
  agir/people/tasks.py
  agir/voting_proxies/tasks.py
Labels: minor bug

#2022 Voting proxy request tweaks
  agir/voting_proxies/actions.py
  agir/voting_proxies/admin/panels.py
  agir/voting_proxies/tests/test_actions.py
Labels: Quickfix

#2020 Fix sentry 2937
  agir/groups/views/api_views.py
Labels: minor bug

#2023 Message promo : remove 'new' label
  agir/groups/components/messages/PromoMessageModal.js
Labels: webdesign

#2026 Event card : fix illustration min height
  agir/front/components/genericComponents/EventCard.js
Labels: minor bug

#2024 Enforce lowercase email for voting proxy requests
  .hypothesis/examples/95dc7b7ff0e493cd/014ee95070ab0b54
  .hypothesis/examples/a8f3af75ba35d1d2/5f356caa5f875b9f
  agir/voting_proxies/actions.py
Labels: minor bug

#2025 Remove broken and no more relevant vpr test
  .hypothesis/examples/5b721dd590d22e25/9308600df9787642
  .hypothesis/examples/6a2e6cafece44878/24787749454896c9
  .hypothesis/examples/ddb76f4f03fab698/1309a0e0a408196d
  .hypothesis/examples/ddb76f4f03fab698/380f96e0f0db7b72
  .hypothesis/examples/f3043d07df515730/4303845783b0d222
  agir/voting_proxies/tests/test_actions.py
Labels: feature

#2027 Send unconfirmed vpr message to proxies
  .hypothesis/examples/6e8be5e69c554c1f/23e27ad759ecdfc6
  .hypothesis/examples/a8f3af75ba35d1d2/e7917d36ec88ecae
  .hypothesis/examples/ddb76f4f03fab698/4655984455fc6da5
  .hypothesis/examples/e3879ab8af5e6fa2/b02ba649c22f884d
  .hypothesis/examples/e3879ab8af5e6fa2/b4898a229c101d44
  agir/voting_proxies/management/commands/fulfill_voting_proxy_requests.py
  agir/voting_proxies/management/commands/send_voting_proxy_confirmation_reminder.py
  agir/voting_proxies/tasks.py
Labels: feature

#2030 Events : fix past events duplicates
  agir/events/views/api_views.py
Labels: bug

#2032 Voting proxy confirmation page
  .hypothesis/examples/5b721dd590d22e25/541b43e795f0ecf4
  .hypothesis/examples/6a2e6cafece44878/88ceabb31a63e566
  .hypothesis/examples/6a2e6cafece44878/8fac05b62dc08009
  .hypothesis/examples/6a2e6cafece44878/fdf654d754ade524
  .hypothesis/examples/6e8be5e69c554c1f/f2459b6de92989f6
  .hypothesis/examples/95dc7b7ff0e493cd/2cd4dd420ca9fb14
  .hypothesis/examples/95dc7b7ff0e493cd/d4508f471781b8ea
  .hypothesis/examples/e3879ab8af5e6fa2/df2715048a9397ac
  agir/front/components/app/routes.config.js
  agir/front/urls.py
  agir/front/views.py
  agir/lib/components/utils/url.js
  agir/voting_proxies/components/VotingProxy/ReplyToVotingProxyRequests/AcceptedRequests.js
  agir/voting_proxies/components/VotingProxy/ReplyToVotingProxyRequests/ReplyToVotingProxyRequests.js
  agir/voting_proxies/components/VotingProxy/ReplyToVotingProxyRequests/ReplyingForm.js
  agir/voting_proxies/tasks.py
  agir/voting_proxies/views.py
Labels: feature

#2031 Admin : fix group donation display
  agir/lib/display.py
  agir/payments/admin.py
Labels: bug-staging

#2033 Static toast : styles
  agir/front/components/genericComponents/StaticToast.js
Labels: webdesign

#2035 Remove needed authentication from voting proxy accepted request page
  agir/front/components/app/routes.config.js
  agir/front/urls.py
  agir/front/views.py
  agir/voting_proxies/components/VotingProxy/NewVotingProxy/NewVotingProxySuccess.js
  agir/voting_proxies/views.py
Labels: feature, bug-staging

#2037 Event creation : filter restricted subtypes allowed on election dates
  agir/events/components/createEventPage/CreateEvent.js
  agir/events/components/createEventPage/EventForm/SubtypeField.js
  agir/events/components/createEventPage/EventForm/index.js
Labels: feature

#2036 Voting proxy request tweaks
  .hypothesis/examples/6e8be5e69c554c1f/fabee51912356cde
  .hypothesis/examples/95dc7b7ff0e493cd/3ab782771798e285
  .hypothesis/examples/df274aa83beb1e49/03ea683b34bb0386
  .hypothesis/examples/e3879ab8af5e6fa2/56c2b047658927c4
  .hypothesis/examples/f3043d07df515730/c32ac63f827b7d15
  agir/voting_proxies/actions.py
  agir/voting_proxies/admin/panels.py
  agir/voting_proxies/components/Common/StyledComponents.js
  agir/voting_proxies/components/Common/StyledPageContainer.js
  agir/voting_proxies/components/VotingProxy/NewVotingProxy/NewVotingProxyHowTo.js
  agir/voting_proxies/components/VotingProxy/ReplyToVotingProxyRequests/ReplyingForm.js
  agir/voting_proxies/components/VotingProxyRequest/NewVotingProxyRequest/NewVotingProxyRequestHowTo.js
  agir/voting_proxies/components/VotingProxyRequest/VotingProxyRequestDetails/VotingProxyRequestDetails.js
  agir/voting_proxies/models.py
  agir/voting_proxies/views.py
Labels: feature

#2038 Event create/update : restricted subtypes on election dates with timezone
  agir/events/components/EventSettings/EventGeneral.js
  agir/events/components/EventSettings/EventSubtypeField.js
  agir/events/components/createEventPage/CreateEvent.js
  agir/events/components/createEventPage/EventForm/index.js
Labels: feature

#2040 Voting proxy request cancellation by owners
  .hypothesis/examples/f3043d07df515730/5be636edc3a25a1b
  agir/voting_proxies/actions.py
  agir/voting_proxies/admin/panels.py
  agir/voting_proxies/components/Common/api.js
  agir/voting_proxies/components/VotingProxyRequest/VotingProxyRequestDetails/VotingProxyRequestDetails.js
  agir/voting_proxies/components/VotingProxyRequest/VotingProxyRequestDetails/VotingProxyWidget.js
  agir/voting_proxies/models.py
  agir/voting_proxies/tasks.py
  agir/voting_proxies/urls.py
  agir/voting_proxies/views.py
Labels: feature

#2041 Event creation : match elections dates to outre-mer zipcodes
  agir/events/components/createEventPage/EventForm/index.js
Labels: bug-staging

#2043 Event dates election: remove zipcodes that dont vote before metropole
  agir/events/components/EventSettings/EventGeneral.js
  agir/events/components/createEventPage/CreateEvent.js
  agir/events/components/createEventPage/EventForm/index.js
Labels: bug-staging

#2047 Fix voting proxy wrong information
  agir/voting_proxies/models.py
Labels: bug, Quickfix

#2050 Voting proxy request cancellation by proxy
  .hypothesis/examples/df274aa83beb1e49/bc1798b3cfa726de
  agir/voting_proxies/actions.py
  agir/voting_proxies/components/Common/api.js
  agir/voting_proxies/components/VotingProxy/ReplyToVotingProxyRequests/AcceptedRequests.js
  agir/voting_proxies/tasks.py
  agir/voting_proxies/urls.py
  agir/voting_proxies/views.py
Labels: feature

#2051 Event & Group creation : redirect to Treve page during election dates
  agir/events/components/createEventPage/CreateEvent.js
  agir/front/components/app/routes.components.js
  agir/front/components/app/routes.config.js
  agir/front/components/treveCreationPage/TreveCreationPage.js
  agir/front/components/treveCreationPage/TreveCreationPage.stories.js
  agir/front/urls.py
  agir/groups/views/management_views.py
Labels: feature

#2057 Fix treve date
  agir/events/components/createEventPage/CreateEvent.js
  agir/groups/views/management_views.py
Labels: bug

#2060 Treve page : add button agir
  agir/front/components/treveCreationPage/TreveCreationPage.js
Labels: feature

#2059 Fix voting proxy creation error with different case email
  .hypothesis/examples/6e8be5e69c554c1f/931c3b759698c37c
  .hypothesis/examples/df274aa83beb1e49/3aa32cafec747e29
  agir/voting_proxies/actions.py
Labels: minor bug

#2067 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#2073 Add segment registration date before field
  agir/mailing/admin.py
  agir/mailing/migrations/0041_segment_registration_date_before.py
  agir/mailing/models.py
Labels: Quickfix

#2074 Fix person form segment check
  agir/people/person_forms/models.py
Labels: Quickfix

#2075 Fix pollparticipationview segment checks
  agir/polls/views.py
Labels: Quickfix

#2076 feat: add unauthorized_message field to Poll model
  agir/polls/admin.py
  agir/polls/migrations/0018_poll_unauthorized_message.py
  agir/polls/models.py
  agir/polls/templates/polls/detail.html
  agir/polls/views.py
Labels: Quickfix

#2082 chore: update NPM dependencies
  package-lock.json
  package.json
Labels: javascript, dependencies

#2083 Fix voting proxy polling station select
  agir/mailing/static/mosaico_templates/versafix-jlm2022/edres/melenchon2022LogoBlock.png
  agir/mailing/static/mosaico_templates/versafix-jlm2022/img/logo.jpg
  agir/mailing/static/mosaico_templates/versafix-jlm2022/img/logo.png
  agir/mailing/static/mosaico_templates/versafix-jlm2022/template.html
  agir/voting_proxies/components/VotingProxy/NewVotingProxy/VotingProxyForm.js
  agir/voting_proxies/components/VotingProxyRequest/NewVotingProxyRequest/VotingProxyRequestForm.js
  agir/voting_proxies/components/VotingProxyRequest/NewVotingProxyRequest/form.config.js
  agir/voting_proxies/models.py
  agir/voting_proxies/tasks.py
Labels: bug-staging

#2089 Group certification panel
  .hypothesis/examples/ddb76f4f03fab698/4156405519fa4976
  .hypothesis/examples/df274aa83beb1e49/43b79de6cec0ffb5
  agir/front/components/genericComponents/ObjectManagement/ManagementMenu.js
  agir/front/urls.py
  agir/groups/admin/panels.py
  agir/groups/components/groupPage/GroupSettings/GroupCertificationPage/CertificationStatus.js
  agir/groups/components/groupPage/GroupSettings/GroupCertificationPage/CertificationStatus.stories.js
  agir/groups/components/groupPage/GroupSettings/GroupCertificationPage/GroupCertification.js
  agir/groups/components/groupPage/GroupSettings/GroupCertificationPage/GroupCertification.stories.js
  agir/groups/components/groupPage/GroupSettings/GroupCertificationPage/index.js
  agir/groups/components/groupPage/GroupSettings/GroupSettings.js
  agir/groups/components/groupPage/GroupSettings/routes.config.js
  agir/groups/components/utils/group.js
  agir/groups/models.py
  agir/groups/serializers.py
  babel.config.json
  jest.config.js
  package-lock.json
  package.json
Labels: feature

#2086 Handle IntegrityError in new_event_suggestion_notification to avoid blocking suggest_event
  .hypothesis/examples/5b721dd590d22e25/919493661265fde8
  .hypothesis/examples/95dc7b7ff0e493cd/72589a9cbb6f65db
  .hypothesis/examples/df274aa83beb1e49/d9c9f3d67beed0be
  agir/events/actions/notifications.py
Labels: bug
